-----Cac bang them moi
CREATE TABLE WH_DOCUMENT
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(10,0), 
	"CREDIT_APP_ID" NUMBER(10,0), 
	"DOC_TYPE" NUMBER(10,0), 
	"BATCH_ID" NUMBER(30,0), 
	"ORDER_BY" NUMBER(10,0), 
	"ESTIMATE_DATE" DATE, 
	"WH_CODE_ID" NUMBER(10,0), 
	"WH_LODGE_DATE" DATE, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(35 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(35 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"CREDIT_DOCUMENT_ID" NUMBER(10,0), 
	"CONTRACT_CAVET_TYPE" NUMBER(10,0), 
	"STATUS" NUMBER, 
	"WH_LODGE_BY" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_WH_DOCUMENT" PRIMARY KEY ("ID")
   );
CREATE SEQUENCE  "SEQ_WH_DOCUMENT_ID"   MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE WH_CAVET_INFO
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(35 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(35 BYTE), 
	"CREATED_DATE" DATE, 
	"WH_DOC_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BRAND" VARCHAR2(20 BYTE), 
	"MODEL_CODE" VARCHAR2(20 BYTE), 
	"COLOR" VARCHAR2(10 BYTE), 
	"ENGINE" VARCHAR2(10 BYTE), 
	"CHASSIS" VARCHAR2(20 BYTE), 
	"N_PLATE" VARCHAR2(20 BYTE), 
	"CAVET_NUMBER" VARCHAR2(20 BYTE), 
	"TYPE" NUMBER(10,0), 
	"VERSION" NUMBER(10,0), 
	 CONSTRAINT "PK_WH_CAVET_INFO" PRIMARY KEY ("ID")
   );
CREATE SEQUENCE  "SEQ_WH_CAVET_INFO_ID"   MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE WH_MAP_DOC_CODE
   (	"WH_DOC_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"WH_CODE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(35 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	 CONSTRAINT "PK_WH_MAP_DOC_CODE" PRIMARY KEY ("WH_DOC_ID", "WH_CODE_ID")
   );

CREATE TABLE WH_CODE
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(10,0), 
	"CODE" VARCHAR2(20 BYTE), 
	"DOC_TYPE" NUMBER(10,0), 
	"MATERIAL" NUMBER(10,0), 
	 CONSTRAINT "PK_WH_CODE" PRIMARY KEY ("ID")
   );
CREATE SEQUENCE  "SEQ_WH_CODE_ID"   MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE WH_BORROWED_DOCUMENT
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"WH_DOC_ID" NUMBER(10,0), 
	"CREATED_BY" VARCHAR2(35 BYTE), 
	"OBJECT_TO" NUMBER(10,0), 
	"APPOINTMENT_DATE" DATE, 
	"EXTENSION_DATE" DATE, 
	"APPROVE_STATUS" NUMBER(10,0), 
	"APPROVE_DATE" DATE, 
	"APPROVE_BY" VARCHAR2(10 BYTE), 
	"REJECT_REASON" NVARCHAR2(10), 
	"TYPE" NUMBER(10,0), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "PK_WH_BORROWED_DOCUMENT" PRIMARY KEY ("ID")
   );
CREATE SEQUENCE  "SEQ_WH_BORROWED_DOCUMENT_ID"   MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE WH_DOCUMENT_CHANGE
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"WH_DOC_ID" NUMBER(10,0), 
	"TYPE" NUMBER(10,0), 
	"NOTE" NVARCHAR2(500), 
	"CREATED_BY" VARCHAR2(35 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ID_CODE_TABLE" NUMBER(10,0), 
	"APPENDIX_CONTRACT" NUMBER(10,0), 
	"DOCUMENT_TYPE_ID" NUMBER, 
	"SCAN_ID" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_WH_DOCUMENT_CHANGE" PRIMARY KEY ("ID")
   );
CREATE SEQUENCE  "SEQ_WH_DOCUMENT_CHANGE_ID"   MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE WH_LETTER
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"WH_DOC_ID" NUMBER(10,0), 
	"TEMPLATE_ID" NUMBER(10,0), 
	"CREATED_BY" VARCHAR2(35 BYTE), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "PK_WH_LETTER" PRIMARY KEY ("ID")
   );
CREATE SEQUENCE  "SEQ_WH_LETTER_ID"   MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;

 CREATE TABLE ALLOCATION_HISTORY
   (	"ID" NUMBER(15,0) NOT NULL ENABLE, 
	"ALLOCATION_DETAIL_ID" NUMBER(15,0), 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(35 BYTE), 
	"ASSIGNEE_ID" NUMBER(10,0), 
	"STATUS" NUMBER(10,0), 
	"NOTE" VARCHAR2(10 BYTE), 
	 CONSTRAINT "PK_ALLOCATION_HISTORY" PRIMARY KEY ("ID")
   );
CREATE SEQUENCE  "SEQ_ALLOCATION_HISTORY_ID"   MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE TABLE STATE_TRANSACTION_MATRIX
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(35 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODULE" VARCHAR2(20 BYTE), 
	"WORK_FLOW" NUMBER, 
	"RULE_ID" NUMBER, 
	"EXPECTED_RULE_OUTPUT" VARCHAR2(1000 BYTE), 
	"OBJECT_TYPE" VARCHAR2(3 BYTE), 
	"FUNCTION_ID" NUMBER, 
	"STEP" VARCHAR2(3 BYTE), 
	"ACTION_TYPE" VARCHAR2(10 BYTE), 
	"ACTION" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(1 BYTE),
	"MATRIX_CODE" VARCHAR2(20 BYTE),	
	 CONSTRAINT "STATE_TRANSACTION_MATRIX_PK" PRIMARY KEY ("ID")
   );
CREATE SEQUENCE  "SEQ_STATE_TRANSACTION_MATRIX_ID"   MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;   
 

CREATE TABLE INPUT_MATRIX
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FUNCTION_ID" NUMBER(10,0), 
	"CONTRACT_STATUS" VARCHAR2(100 BYTE), 
	"CAVET_STATUS" VARCHAR2(100 BYTE), 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"CODE_GROUP" VARCHAR2(50 BYTE), 
	"CAVET_ERR" VARCHAR2(100 BYTE), 
	"DOC_TYPE" NUMBER, 
	"LETTER_STATUS" VARCHAR2(100 BYTE), 
	 CONSTRAINT "INPUT_MATRIX_PK" PRIMARY KEY ("ID")
   ); 
CREATE SEQUENCE  "SEQ_INPUT_MATRIX_ID"   MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;  


 CREATE TABLE MATRIX_DETAIL
   (	"ID" NUMBER NOT NULL ENABLE, 
	"STATE_TRANSATION_MATRIX_ID" NUMBER, 
	"URL" VARCHAR2(200 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"TYPE_ERR" NUMBER, 
	 CONSTRAINT "MATRIX_DETAIL_PK" PRIMARY KEY ("ID")
   );
CREATE SEQUENCE  "SEQ_MATRIX_DETAIL_ID"   MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;  

commit;


---Them cot ASSIGNER_ID vao bang ALLOCATION_MASTER
ALTER TABLE ALLOCATION_MASTER ADD 
   (
      ASSIGNER_ID             NUMBER
   );
   
--Them cot NOTE vao bang ALLOCATION_DETAIL
ALTER TABLE ALLOCATION_DETAIL ADD 
   (
      NOTE             VARCHAR2(500)
   );
   
--doi ten cot OBJECT_ID thanh assignee_id trong bang allocation_detail
ALTER TABLE allocation_detail
RENAME COLUMN OBJECT_ID TO assignee_id;

--doi ten cot UPL_CUSTOMER_ID thanh upl_object_id trong bang allocation_detail
ALTER TABLE allocation_detail
RENAME COLUMN UPL_CUSTOMER_ID TO upl_object_id;

commit;

-----tao functions get_code_save_wh
create or replace FUNCTION get_code_save_wh (
    doctype IN VARCHAR
) RETURN VARCHAR2 IS
    codesavewh   VARCHAR2(50);
    countsum     NUMBER;
    countt       NUMBER;
    countz        NUMBER;
    counths       NUMBER;
    countCv      NUMBER;
    counttStr    VARCHAR(10);
    countzStr     VARCHAR(10);
    counthsStr    VARCHAR(10);
BEGIN
    --Loai truyen vao la hop dong, hop dong loi hay thu cam on
    IF ((upper(doctype) = 'HĐ') or (upper(doctype) = 'HĐL') or (upper(doctype) = 'TCO')) THEN
        SELECT COUNT(1) INTO countsum FROM wh_code a where a.code like '%'||doctype||'%' ;
        countz := floor(countsum / 20000) + 1;
        if (LENGTH(countz) = 1) then countzStr := '00' || countz;
        elsif (LENGTH(countz) = 2) then countzStr := '0' || countz;
        else
        countzStr := countz;        
        end if;

        countt := floor(MOD(countsum,20000) / 200) + 1;
        if (LENGTH(countt) = 1) then counttStr:= '00' || countt;
        elsif (LENGTH(countt) = 2) then counttStr:= '0' || countt; 
        else
        counttStr := countt;
        end if;

        counths := MOD(MOD(countsum,20000),200) + 1;
        if (LENGTH(counths) = 1) then counthsStr:= '00' || counths;
        elsif (LENGTH(counths) = 2) then counthsStr:= '0' || counths;
        else
        counthsStr := counths;
        end if;  
        codesavewh := countzStr || '-' || upper(doctype) || '-' || counttStr || '-' || counthsStr || '###0';
    ELSIF (upper(doctype) = 'CV') THEN --Loai truyen vao la cavet
        --Tim xem ma cavet nao trong thi gan khong thi sinh ma moi
        select COUNT(1) INTO countCv from wh_code a, code_table b where a.status=b.id and b.code_group='WH' and b.category ='WH_LOGDE' and b.code_value1='WH_LODGED_COMPLETE_RETURN' 
        and ROWNUM=1 ORDER BY a.id;
        IF (countCv = 0) THEN
                SELECT COUNT(1) INTO countsum FROM wh_code a where a.code like '%'||doctype||'%' ;                
                countz := floor(countsum / 15000) + 1;
                if (LENGTH(countz) = 1) then countzStr := '00' || countz;
                elsif (LENGTH(countz) = 2) then countzStr := '0' || countz;
                else
                countzStr := countz;        
                end if;

                countt := floor(MOD(countsum,15000) / 150) + 1;
                if (LENGTH(countt) = 1) then counttStr:= '00' || countt;
                elsif (LENGTH(countt) = 2) then counttStr:= '0' || countt; 
                else
                counttStr := countt;
                end if;

                counths := MOD(MOD(countsum,15000),150) + 1;
                if (LENGTH(counths) = 1) then counthsStr:= '00' || counths;
                elsif (LENGTH(counths) = 2) then counthsStr:= '0' || counths;
                else
                counthsStr := counths;
                end if;
                codesavewh := countzStr || '-' || upper(doctype) || '-' || counttStr || '-' || counthsStr || '###0'; 
        ELSE
            select a.code INTO codesavewh from wh_code a, code_table b where a.status=b.id and b.code_group='WH' and b.category ='WH_LOGDE' and b.code_value1='WH_LODGED_COMPLETE_RETURN' 
        and ROWNUM=1 ORDER BY a.id;
            codesavewh := codesavewh || '###1';
        END IF;       
    ELSE
        DBMS_OUTPUT.PUT_LINE('Doc type is Err'); 
    END IF;        

    RETURN codesavewh;
END;

commit;

--------------Inser du lieu bang CODE_TABLE
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_DOC_TYPE','WH_LOAN_DOC','Hồ sơ khoản vay','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_DOC_TYPE','WH_CAVET','Cavet','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_DOC_TYPE','WH_ERR_UPDATE','Update lỗi','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_DOC_TYPE','WH_THANKS_LETTER','Thư cảm ơn','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_PRG_STATUS','WH_DONE','Đã xử lý','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_PRG_STATUS','WH_NOT_DONE','Chưa xử lý','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_ASS_STATUS','WH_DONE','Đã assign','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_ASS_STATUS','WH_NOT_DONE','Chưa assign','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_ASS_TYPE','WH_ONE','Phân bổ lần 1','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_ASS_TYPE','WH_MANY','Tái phân bổ','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_NEW_WAIT','Mới nhận_Chờ kiểm tra','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_WAIT_COMPLETE','Chờ lưu kho_Hoàn chỉnh','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_WAIT_ERR_UPDATE','Chờ lưu kho_Cần update lỗi','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_LODGED_COMPLETE','Đã lưu kho_Hoàn chỉnh','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_LODGED_ERR_UPDATE','Đã lưu kho_Cần update lỗi','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_LODGED_ERR_UPDATE_BORROW','Đã lưu kho_Cần update lỗi_Đang cho mượn','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_LODGE_COMPLETE_BORROW','Đã lưu kho_Hoàn chỉnh_Đang cho mượn','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_FLOW','WH_IL','IL','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_FLOW','WH_ED','ED','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_FLOW','WH_MC','MC','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_APR_STATUS','WH_WAIT','Chờ phê duyệt cho mượn','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_APR_STATUS','WH_OK','Đã phê duyệt cho mượn','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_APR_STATUS','WH_REJECT','Đã từ chối cho mượn','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_C_LODGE_CV','WH_WRONG_NAME','Sai Họ và tên KH','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_C_LODGE_CV','WH_WRONG_BRAND','Sai Nhãn hiệu xe','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_C_LODGE_CV','WH_WRONG_TYPE_NUM','Sai Số loại','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_C_LODGE_CV','WH_WRONG_CHASSIS','Sai Số Khung','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_C_LODGE_CV','WH_WRONG_ENGINE','Sai Số Máy','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_C_LODGE_CV','WH_EXPIRED_30_DAYS','Cavet gửi về quá 30 ngày kể từ ngày giải ngân','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_C_LODGE_CV','WH_EXPIRED_45_DAYS','Bộ hồ sơ gốc ( giấy tờ thay thế cavet) xe máy gửi về quá 45 ngày kể từ ngày giải ngân','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_C_LODGE_CV','WH_PASS','Cavet đạt - chuyển lưu kho','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_01','ĐNVV kiêm HĐCV không có đầy đủ phần thông tin DSA/TSA','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_02','HĐCV  không hợp lệ','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_03','HĐCV đạt - chuyển lưu kho','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_04','Gửi nhầm HĐBH của KH khác','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_05','Không có HĐBH trong trường hợp KH có mua HĐBH','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_06','HĐBH không hợp lệ','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_07','HĐBH đạt - chuyển lưu kho','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_08','Hồ sơ gốc gửi về TTVH quá 10 ( mười ) ngày làm việc','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_09','Update lỗi gửi quá 15 ( mười lăm ) ngày làm việc','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_10','Sai/ thiếu form checklist, thông tin trên checklist','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_11','QĐHS đạt - chuyển lưu kho','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_12','ĐNVV kiêm HĐCV gửi về không có chữ ký nháy của khách hàng trên các trang','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_13','ĐNVV kiêm HĐCV gửi về không đủ số trang','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_14','Hợp đồng của khách hàng khác với bản cung cấp trên hệ thống ( đánh giá theo từng trường hợp )','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_15','Sai tên hàng hóa, nhãn hiệu, mẫu','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_16','Ký thiếu/ Ký tắt phần ghi rõ họ tên CA/DE/DSA trên liên 2 HĐCV','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_17','Ký thiếu/ Ký tắt phần ghi rõ họ tên CA/DE/DSA trên liên 1 HĐCV','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_18','Ký thiếu/ Ký sai vị trí / Ký tắt phần ghi rõ họ tên khách hàng trên liên 1 hoặc liên 2 HĐCV','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_19','Phần ghi rõ họ tên tại mục  ký, ghi rõ họ tên  của KH trên HĐCV không khớp với tên của KH trên HĐCV','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_20','HĐCV in sai mẫu/ sai form','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_21','HĐCV gửi về có vạch đen không thể xác nhận được thông tin','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_22','HĐCV gửi nhầm của KH khác','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_23','Không có HĐCV','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_NOT_RECEIVE','Chưa nhận','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_LODGED_ERR_UPDATE_RETURN','Đã lưu kho_Cần update lỗi_Xuất trả KH','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_LODGED_COMPLETE_RETURN','Đã lưu kho_Hoàn chỉnh_Xuất trả KH','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_COMPLETE_NOT_RECEIVE','Đã tất toán_Cavet chưa về','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_RETURN_DOC_NOT_RECEIVE','Hoàn trả_Giấy tờ chưa về','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_WAIT_RETURN','Chờ lưu kho_Thư hoàn','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_LODGED_RETURN','Đã lưu kho_Thư hoàn','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_NEW_WAIT_ALLOCATION','Mới nhận_Chờ phân bổ','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_ALLOCATED_WAIT_CHECK','Đã phân bổ_Chờ kiểm tra','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_ASS_TYPE','WH_NOT','Chưa phân bổ','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_LOGDE','WH_NEW_DOCUMENT','Hồ sơ mới','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_DEPARTMENT','WH_MANAGER_DOC','Quản lý hồ sơ khoản vay','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_EMP_POS','WH_DEPT_LEAD','Trưởng bộ phận','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_EMP_POS','WH_GROUP_LEAD','Trưởng nhóm','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_EMP_POS','WH_MANAGER_DOC','Nhân viên/Chuyên viên','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_BRW_TYPE','WH_CAVET','Cavet','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_BRW_TYPE','WH_HSKV','Hồ sơ khoản vay','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_ERR','Các loại lỗi','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_APP_CAVET_BR','Phê duyệt cho mượn Cavet','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_APP_CAVET_R','Phê duyệt xuất trả Cavet','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_APP_BORROW','Cho mượn','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_APP_RE_BORROW','Gia hạn ','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_APP_RE_BORROW_HD','Gia hạn HSKV','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_APP_RE_BORROW_CV','Gia hạn cavet','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_APP_BORROW_HD','Cho mượn HSKV','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_APP_BORROW_CV','Cho mượn Cavet','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_UPDATE_ERR','WH_UPDATE_ERR_HD','Update lỗi cho hợp đồng','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_UPDATE_ERR','WH_UPDATE_ERR_CV','Update lỗi cho CAVAT','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_MATERIAL','WH_PAPER','Giấy','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_MATERIAL','WH_PLASTIC','Nhựa','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_MATERIAL','WH_WOOD','Gỗ','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_MATERIAL','WH_METAL','Kim loại','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_STATUS_CHANGE','Thay đổi trạng thái loại giấy tờ','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_RE_STATUS','WH_WAIT_RETURN','Chờ phê duyệt xuất trả','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_RE_STATUS','WH_OK_RETURN','Đã phê duyệt xuất trả','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_RE_STATUS','WH_REJECT_RETURN','Đã từ chối xuất trả','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_RE_STATUS','WH_RETURN','Đã xuất trả','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_SAVE_TRANSFER','WH_LODGE_TMP','Lưu kết quả kiểm tra hồ sơ HĐCV','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_STATUS_DOC','WH_STATUS_24','Khác','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CAVET_TYPE','WH_IN_CAVET','Thông tin CAVET trên CAVET','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CAVET_TYPE','WH_IN_APPENDIX','Thông tin CAVET trên phục lục','A');
insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,null, null, 0, 0, 0, 'WH','WH_CHAN_TYPE','WH_DOC_TYPE_CHANGE','Thay đổi loại giấy tờ','A');

commit;





