package com.mcredit.sharedbiz.validation;

public interface PaymentalidationConstants {
	String SERVICER_NAME_CREATEPAYMENT = "create_payment";
	String SERVICER_NAME_PAYMENT_CREDIT_CARD = "payment_credit_card";
	String SERVICER_NAME_MAKE_TRANSFER ="make_transfer";
	String SERVICER_NAME_SMS_QUEUE = "sms_queue";	
	
	String VAL_POSTINGCONFIGURATION_DEBITOWNER_C = "C";
	String VAL_POSTINGCONFIGURATION_DEBITOWNER_P = "P";
	String VAL_POSTINGCONFIGURATION_DEBITOWNER_U = "U";
	String VAL_POSTINGCONFIGURATION_DEBITOWNER_I = "I";
	String PAYMENT_FROM_CHANEL = "MCP" ;
	String VAL_POSTINGCONFIGURATION_POSTINGSYSTEM_T24 = "T24";
	String VAL_POSTINGCONFIGURATION_POSTINGSYSTEM_WAY4 = "W4";
	String VAL_POSTINGCONFIGURATION_AMOUNTTAG_CRED_AMT = "CRED_AMT";
	String VAL_POSTINGCONFIGURATION_AMOUNTTAG_CRED_AMT_MINUS_INSU = "CRED_AMT_MINUS_INSU";
	String VAL_POSTINGCONFIGURATION_AMOUNTTAG_FEE_COLLECT_AMT = "FEE_COLLECT_AMT";
	String VAL_POSTINGCONFIGURATION_AMOUNTTAG_TRANS_AMT = "TRANS_AMT";
	String VAL_POSTINGCONFIGURATION_AMOUNTTAG_TRANS_AMT_MINUS_FEE = "AMT_MINUS_FEE";
	

}
