create table MESSAGE_LOG(id 	number(17,0) default on null  	Sequence,
msg_type 	varchar2(1),
from_channel 	varchar2(3) default on null 'BPM',
to_channel 	varchar2(3) default on null 'T24',
relation_id 	varchar2(40),
trans_id 	number(17,0) default on null  	0,
trans_type 	varchar2(10) default on null 'ISSCARD',
service_name 	varchar2(200),
response_code 	varchar2(10),
response_error_desc 	varchar2(255),
msg_order 	number(2) default on null  	1,
msg_request 	clob,
msg_response 	clob,
msg_status 	varchar2(1) default on null 'N',
request_time 	timestamp,
process_time 	timestamp,
response_time 	timestamp,
response_payload_id 	varchar2(30),
CONSTRAINT PK_MESSAGE_LOG PRIMARY KEY (id))
LOB (msg_request, msg_response) STORE AS BASICFILE (TABLESPACE MCPORTAL_LOB CHUNK 4096 
                  RETENTION 
                  NOCACHE LOGGING 
                  STORAGE (MAXEXTENTS 5)
);

create table CUST_PERSONAL_INFO(id 	number(13,0),
mc_cust_code 	varchar2(20) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
core_cust_code 	varchar2(30),
cust_name 	varchar2(100) not null,
short_cust_name 	varchar2(100),
other_cust_name 	varchar2(100),
identity_id 	number(13,0) not null,
gender 	int,
birth_date 	date,
household_reg_number 	varchar2(50),
household_reg_type_id 	int,
household_reg_issue_date 	date,
household_reg_issue_place 	varchar2(100),
home_phone 	varchar2(50),
marital_status 	int,
is_prospect 	varchar2(1),
CONSTRAINT PK_CUST_PERSONAL_INFO PRIMARY KEY (id));

create table CUST_ADDL_INFO(id 	number(13,0),
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
month_experience 	int,
year_experience 	int,
ref_full_name1 	varchar2(100),
ref_full_name2 	varchar2(100),
income_spouse 	number(13,2),
lifetime_in_month 	int,
lifetime_in_year 	int,
ref_person1_mobile 	varchar2(50),
ref_person2_mobile 	varchar2(50),
number_of_dependants 	int,
relation_spouse 	int,
relation_ref_person1 	int,
relation_ref_person2 	int,
spouse_company_name 	varchar2(255),
spouse_DOB 	date,
spouse_identity_number 	varchar2(50),
spouse_mobile 	varchar2(50),
spouse_name 	varchar2(100),
spouse_position 	int,
education 	int,
temp_same_perm_addr 	int,
old_identity_number 	varchar2(50),
military_id 	varchar2(50),
military_issue_date 	date,
military_issue_place 	varchar2(50),
labour_contract_type 	int,
payroll_method 	int,
accommodation_type 	int,
is_black_list 	int,
black_list_type 	int,
professional 	int,
department 	varchar2(100),
position_in_comp 	int,
cust_company_id 	int,
CONSTRAINT PK_CUST_ADDL_INFO PRIMARY KEY (id));

create table CUST_FINANCIAL_INFO(id 	number(13,0),
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
credit_in_other_bank 	varchar2(1),
spouse_credit_in_other_bank 	varchar2(1),
s37_data 	int,
cust_income 	number(13,2),
life_insu_company_id 	int,
insu_term 	int,
insu_term_fee 	number(13,2),
insu_term_other 	varchar2(50),
payment_amount_at_bank 	number(13,2),
account_number_at_bank 	varchar2(50),
bank_name 	varchar2(50),
bank_branch 	varchar2(100),
avg_account_bal 	number(13,2),
avg_electric_bill 	number(13,2),
CONSTRAINT PK_CUST_FINANCIAL_INFO PRIMARY KEY (id));

create table CUST_CONTACT_INFO(id 	number(13,0),
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
contact_type 	int not null,
contact_priority 	int default on null  	1 not null,
contact_value 	varchar2(100),
CONSTRAINT PK_CUST_CONTACT_INFO PRIMARY KEY (id));

create table CUST_COMPANY_INFO(id 	int,
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
comp_addr_street 	varchar2(255),
comp_addr_province 	int,
comp_addr_district 	int,
comp_addr_ward 	int,
comp_name 	varchar2(255) not null,
comp_tax_number 	varchar2(50),
office_phone_number 	varchar2(50),
CONSTRAINT PK_CUST_COMPANY_INFO PRIMARY KEY (id));

create table CUST_ACCOUNT_LINK(id 	number(13,0),
cust_id 	number(13,0) default on null  	0 not null,
link_type 	varchar2(1) default on null 'A' not null,
link_seq 	int default on null  	1 not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
link_value 	varchar2(30) not null,
link_name 	varchar2(100),
link_system 	varchar2(3) not null,
link_currency 	varchar2(3) default on null 'VND',
link_product 	varchar2(10),
accounting_code 	varchar2(20),
CONSTRAINT PK_CUST_ACCOUNT_LINK PRIMARY KEY (id));

create table CUST_IDENTITY(id 	number(13,0),
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
identity_number 	varchar2(30) not null,
identity_issue_date 	date,
identity_issue_place 	varchar2(50),
identity_expiry_date 	date,
identity_type_id 	int not null,
CONSTRAINT PK_CUST_IDENTITY PRIMARY KEY (id));

create table CREDIT_APP_REQUEST(id 	number(15,0),
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
rate_index 	int,
int_rate 	number(13,5) not null,
ln_amount 	number(13,2) not null,
ln_amount_minus_insu 	number(13,2),
ln_end_date 	date,
ln_purpose 	int,
ln_other_purpose 	varchar2(100),
ln_start_date 	date,
ln_tenor 	int not null,
payment_date 	date,
sale_id 	int,
product_id 	int not null,
trans_office_id 	int,
contract_date 	date,
apply_to_object 	int,
has_insurance 	int,
insu_amount 	number(13,2),
insu_company 	int,
insu_staffId 	int,
insu_fee 	number(13,2),
insu_type 	int,
insu_rate 	number(13,2),
mc_contract_number 	varchar2(20),
status 	varchar2(1),
disbursement_channel 	int,
disbursement_method 	int,
is_duplicated 	int,
duplicated_note 	varchar2(2000),
scope 	int,
CONSTRAINT PK_CREDIT_APP_REQUEST PRIMARY KEY (id));

create table CREDIT_APP_LMS(id 	number(15,0),
credit_app_id 	number(15,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
core_ln_app_id 	varchar2(20),
disbursement_date 	date,
disbursement_status 	int,
first_payment_date 	date,
last_payment_date 	date,
disbursement_amount 	number(13,2),
CONSTRAINT PK_CREDIT_APP_LMS PRIMARY KEY (id));

create table CREDIT_APP_APPRAISAL(id 	number(15,0),
credit_app_id 	number(15,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
approved_amount 	number(13,2) not null,
approved_date 	date not null,
approved_user 	int not null,
industry	int,
CONSTRAINT PK_CREDIT_APP_APPRAISAL PRIMARY KEY (id));

create table CREDIT_APP_BPM(id 	number(15,0),
credit_app_id 	number(15,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
bpm_id 	number(15,0) not null,
bpm_app_id 	varchar2(32) not null,
bpm_app_number 	number(10,0) not null,
CONSTRAINT PK_CREDIT_APP_BPM PRIMARY KEY (id));

create table CREDIT_APP_TRAIL(id 	number(15,0),
credit_app_id 	number(15,0) not null,
trail_seq 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
step 	int,
task_id 	varchar2(32),
from_user 	int,
to_user 	int,
to_team 	int,
action 	int,
reason_id 	int,
user_comment 	varchar2(4000),
CONSTRAINT PK_CREDIT_APP_TRAIL PRIMARY KEY (id));

create table CREDIT_APP_COMMODITIES(id 	number(15,0),
credit_app_id 	number(15,0) not null,
comm_seq 	int not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
comm_id 	int not null,
frame_number 	varchar2(30),
price 	number(13,2),
serial_number 	varchar2(30),
model 	varchar2(50),
sip_id 	int,
advance_amount 	number(13,2),
discount_rate 	number(13,5),
CONSTRAINT PK_CREDIT_APP_COMMODITIES PRIMARY KEY (id));

create table COMM_BRAND(record_status     varchar2(1) default on null 'A' not null,
brand_id     int not null,
comm_id     int not null,
CONSTRAINT PK_COMM_BRAND PRIMARY KEY (brand_id,comm_id));

create table CODE_TABLE(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
parent_id 	int,
product_cat_id 	int default on null  	0,
product_group_id 	int default on null  	0,
product_id 	int default on null  	0,
code_group 	varchar2(5) not null,
category 	varchar2(10) not null,
code_value1 	varchar2(30),
code_value2 	varchar2(50),
code_message_key 	varchar2 (100),
description1 	varchar2(200),
description2 	varchar2(200),
status 	varchar2(1) default on null 'A',
reference 	varchar2(100),
CONSTRAINT PK_CODE_TABLE PRIMARY KEY (id));

create table USERS(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
login_id 	varchar2(30) not null,
manager_id 	int,
usr_full_name 	varchar2(100),
usr_type 	varchar2(1) not null,
usr_group 	varchar2(20) not null,
sale_code 	varchar2(50),
mobile 	varchar2(50),
sale_network_id 	int,
status 	varchar2(1),
start_eff_date 	date not null,
end_eff_date 	date default on null  	to_date('31-DEC-9999') not null,
CONSTRAINT PK_USERS PRIMARY KEY (id));

create table FUNCTIONS(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
module 	varchar2 (4),
function_code 	varchar2 (10) not null,
description 	varchar2 (100),
menu_id 	int not null,
page_file 	varchar2 (32),
page_access_right 	varchar2 (20) default on null 'NNNNYNNNN' not null,
url 	varchar2 (105),
status 	varchar2 (1),
CONSTRAINT PK_FUNCTIONS PRIMARY KEY (id));

create table SERVICES(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
module 	varchar2 (4),
service_name 	varchar2 (40) not null,
description 	varchar2 (100),
service_access_right 	varchar2 (1) default on null 'Y' not null,
service_path 	varchar2 (105),
posting_group 	varchar2(3),
status 	varchar2 (1),
CONSTRAINT PK_SERVICES PRIMARY KEY (id));

create table FIELDS(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
function_id 	int not null,
service_id 	int not null,
field_message_key 	varchar2(100),
field_name 	varchar2(100),
field_ui_id 	varchar2(50),
field_object_id 	varchar2(50),
field_access_right 	varchar2 (20) default on null 'NNNNYNNNN' not null,
status 	varchar2 (1),
CONSTRAINT PK_FIELDS PRIMARY KEY (id));

create table MENU(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
module 	varchar2 (4),
menu_code 	varchar2 (10) not null,
menu_title 	varchar2 (100),
menu_message_key 	varchar2 (100),
parent_menu 	varchar2 (10),
status 	varchar2 (1),
CONSTRAINT PK_MENU PRIMARY KEY (id));

create table ROLES(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
role_code 	varchar2 (10) not null,
role_type 	varchar2 (1),
role_name 	varchar2 (100),
status 	varchar2 (1),
CONSTRAINT PK_ROLES PRIMARY KEY (id));

create table ROLE_DETAILS(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
object_type 	varchar2(1) not null,
role_id 	int not null,
object_id 	int not null,
access_right 	varchar2 (20) default on null 'NNNNYNNNN' not null,
status 	varchar2 (1),
CONSTRAINT PK_ROLE_DETAILS PRIMARY KEY (id));

create table USERS_ROLE_MAPPING(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
user_id 	int not null,
object_type 	varchar2(1) not null,
object_id 	int not null,
access_right 	varchar2 (20) default on null 'NNNNYNNNN' not null,
status 	varchar2 (1),
CONSTRAINT PK_USERS_ROLE_MAPPING PRIMARY KEY (id));

create table USERS_SESSION(id 	int,
login_id 	varchar2(30) not null,
session_key 	varchar2(50),
channel_id 	int,
partner_id 	int,
last_update_date 	date default on null  	sysdate not null,
service_name 	varchar2(50),
function_code 	varchar2 (10),
CONSTRAINT PK_USERS_SESSION PRIMARY KEY (id));

create table PRODUCTS(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
product_category_id 	int,
product_group_id 	int not null,
product_code 	varchar2(10) not null,
product_name 	varchar2(100),
ccy 	varchar2(3) default on null 'VND' not null,
pti 	number(13,5),
tenor 	int,
min_tenor 	int,
max_tenor 	int,
rate_index 	int,
late_rate_index 	int,
late_penalty_fee 	number(13,2),
pre_liquidation_fee 	number(13,2),
max_quantity_commodities 	int,
max_loan_amount 	number(13,2),
min_loan_amount 	number(13,2),
status 	varchar2(1),
start_eff_date 	date not null,
end_eff_date 	date default on null  	to_date('31-DEC-9999') not null,
CONSTRAINT PK_PRODUCTS PRIMARY KEY (id));

create table INTEREST_TABLE(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
rate_type 	varchar2(1) default on null 'F' not null,
rate_code 	varchar2(10) not null,
rate_name 	varchar2(100),
monthly_rate 	number(13,5),
yearly_rate 	number(13,5),
spread 	number(13,5),
max_rate 	number(13,5),
min_rate 	number(13,5),
status 	varchar2(1),
start_eff_date 	date not null,
end_eff_date 	date default on null  	to_date('31-DEC-9999') not null,
CONSTRAINT PK_INTEREST_TABLE PRIMARY KEY (id));

create table GLOBAL_CHECKLIST(id 	int,
checklist_category 	varchar2(1) not null,
checklist_category_id 	int not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
checklist_name 	varchar2(100),
status 	varchar2(1),
start_eff_date 	date not null,
end_eff_date 	date default on null  	to_date('31-DEC-9999') not null,
CONSTRAINT PK_GLOBAL_CHECKLIST PRIMARY KEY (id));

create table PRODUCT_CHECKLIST_DOCUMENT(id     int,
global_checklist_id     int not null,
product_id     int not null,
document_id     int not null,
record_status     varchar2(1) default on null 'A' not null,
created_date     date default on null      sysdate not null,
last_updated_date     date default on null      sysdate not null,
created_by     varchar2(30),
last_updated_by     varchar2(30),
mandatory     varchar2(1) not null,
document_originality     varchar2(1) not null,
step     int,
is_lodge_require     varchar2(1),
allow_temp_uplift     varchar2(1),
document_code     varchar2(20),
CONSTRAINT PK_PRODUCT_CHECKLIST_DOCUMENT PRIMARY KEY (id));

create table CREDIT_APP_CHECKLIST_DOCUMENT(id 	number(15,0),
credit_app_id 	number(15,0) not null,
product_checklist_id 	int not null,
document_id 	int not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
is_mandatory 	varchar2(1) not null,
is_required 	varchar2(1) not null,
document_originality 	varchar2(1) not null,
step 	int,
is_lodge_require 	varchar2(1),
allow_temp_uplift 	varchar2(1),
is_lodged 	varchar2(1),
document_code 	varchar2(20),
document_bar_code 	varchar2(30),
CONSTRAINT PK_CREDIT_APP_CHECKLIST_DOCUMENT PRIMARY KEY (id));

create table GLOBAL_DOCUMENT(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
document_originality 	varchar2(1) not null,
document_name 	varchar2(100),
step 	int,
is_lodge_require 	varchar2(1),
allow_temp_uplift 	varchar2(1),
CONSTRAINT PK_GLOBAL_DOCUMENT PRIMARY KEY (id));

create table POSTING_CONFIGURATION(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
posting_group 	varchar2(3) not null,
posting_order 	int default on null  	1 not null,
transaction_type 	int not null,
debit_owner 	varchar2(1) default on null 'C' not null,
debit_branch 	varchar2(10) not null,
debit_ccy 	varchar2(3) default on null 'VND' not null,
debit_account 	varchar2(20) not null,
credit_owner 	varchar2(1) default on null 'C' not null,
credit_branch 	varchar2(10) not null,
credit_ccy 	varchar2(3) default on null 'VND' not null,
credit_account 	varchar2(20) not null,
amount 	number(13,2),
amount_tag 	varchar2(20) not null,
posting_system 	varchar2(3) default on null 'T24' not null,
CONSTRAINT PK_POSTING_CONFIGURATION PRIMARY KEY (id));

create table POSTING_INSTANCE(id 	number(15,0),
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
posting_group 	varchar2(3) not null,
posting_order 	int default on null  	1 not null,
transaction_type 	varchar2(10) not null,
debit_owner 	varchar2(1) default on null 'C' not null,
debit_branch 	varchar2(10) not null,
debit_ccy 	varchar2(3) default on null 'VND' not null,
debit_account 	varchar2(20) not null,
credit_owner 	varchar2(1) default on null 'C' not null,
credit_branch 	varchar2(10) not null,
credit_ccy 	varchar2(3) default on null 'VND' not null,
credit_account 	varchar2(20) not null,
amount 	number(13,2),
cust_or_partner_id 	number(13,0),
ft_ref_number 	varchar2(30),
status 	varchar2(1) default on null 'N' not null,
CONSTRAINT PK_POSTING_INSTANCE PRIMARY KEY (id));

create table SCHEDULER(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
schedule_group 	varchar2(3) not null,
sch_name 	varchar2(50),
frequency 	varchar2(1) not null,
interval 	int not null,
start_time 	date not null,
next_schedule_time 	date,
status 	varchar2(1) default on null 'S' not null,
num_of_run 	int default on null  	0,
request 	varchar2(255),
allow_overlap 	varchar2(1) default on null 'N' not null,
CONSTRAINT PK_SCHEDULER PRIMARY KEY (id));

create table SCHEDULE_INSTANCE(id 	number(17,0),
schedule_id 	int not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
start_time 	date not null,
end_time 	date,
status 	varchar2(1),
response_code 	varchar2(10),
message 	varchar2(255),
CONSTRAINT PK_SCHEDULE_INSTANCE PRIMARY KEY (id));

create table PARTNER(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
partner_code 	varchar2(10),
partner_name 	varchar2(100),
partner_acct_in_corebank 	varchar2(30),
status 	varchar2(1),
CONSTRAINT PK_PARTNER PRIMARY KEY (id));

create table CREDIT_APP_ADDITIONAL(id 	number(15,0),
credit_app_id 	number(15,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
card_holder_name 	varchar2(100),
is_IB_allowed 	int,
receive_card_addr 	int,
issue_fee_coll 	int,
difference_issue_fee 	number(13,2),
annual_fee_coll 	int,
annual_fee_frequency 	int,
difference_annual_fee 	number(13,2),
insu_fee_coll 	int,
insu_fee_frequency 	int,
difference_insu_fee 	number(13,2),
CONSTRAINT PK_CREDIT_APP_ADDITIONAL PRIMARY KEY (id));

create table PARAMETERS(param_name 	varchar2(20),
param_value 	varchar2 (50) not null,
param_data_type 	varchar2(1) not null,
param_description 	varchar2(100),
status 	varchar2(1) default on null 'A' not null,
CONSTRAINT PK_PARAMETERS PRIMARY KEY (param_name));

=======
create table MESSAGE_LOG(id	number(17,0),
msg_type	varchar2(1),
from_channel	varchar2(3) default on null 'BPM',
to_channel	varchar2(3) default on null 'T24',
relation_id	varchar2(40),
trans_id	number(17,0),
trans_type	varchar2(10) default on null 'ISSCARD',
service_name	varchar2(50),
response_code	varchar2(10),
response_error_desc	varchar2(255),
msg_order		number(2) default on null 1,
msg_request		clob,
msg_response	clob,
msg_status	varchar2(1) default on null 'N',
request_time	timestamp default on null current_timestamp,
process_time	timestamp,
response_time	timestamp,
CONSTRAINT PK_MESSAGE_LOG PRIMARY KEY (id))
LOB (msg_request, msg_response) STORE AS BASICFILE (TABLESPACE MCPORTAL_LOB CHUNK 4096 
                  RETENTION 
                  NOCACHE LOGGING 
                  STORAGE (MAXEXTENTS 5)
);

create table CUST_PERSONAL_INFO(id 	number(13,0),
mc_cust_code 	varchar2(20) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
core_cust_code 	varchar2(30),
cust_name 	varchar2(100) not null,
short_cust_name 	varchar2(100),
other_cust_name 	varchar2(100),
identity_id 	number(13,0) not null,
gender 	varchar2(1),
birth_date 	date,
household_reg_number 	varchar2(50),
household_reg_type_id 	int,
household_reg_issue_date 	date,
household_reg_issue_place 	varchar2(100),
home_phone 	varchar2(50),
marital_status 	int,
is_prospect 	varchar2(1),
CONSTRAINT PK_CUST_PERSONAL_INFO PRIMARY KEY (id));

create table CUST_ADDL_INFO(id 	number(13,0),
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
month_experience 	int,
year_experience 	int,
ref_full_name1 	varchar2(100),
ref_full_name2 	varchar2(100),
income_spouse 	number(13,2),
lifetime_in_month 	int,
lifetime_in_year 	int,
ref_person1_mobile 	varchar2(50),
ref_person2_mobile 	varchar2(50),
number_of_dependants 	int,
relation_spouse 	int,
relation_ref_person1 	int,
relation_ref_person2 	int,
spouse_company_name 	varchar2(255),
spouse_DOB 	date,
spouse_identity_number 	varchar2(50),
spouse_mobile 	varchar2(50),
spouse_name 	varchar2(100),
spouse_position 	int,
education 	int,
temp_same_perm_addr 	varchar2(1),
old_identity_number 	varchar2(50),
military_id 	varchar2(50),
military_issue_date 	date,
military_issue_place 	varchar2(50),
labour_contract_type 	int,
payroll_method 	int,
accommodation_type 	int,
is_black_list 	varchar2(1),
black_list_type 	int,
professional 	int,
department 	varchar2(100),
position_in_comp 	int,
cust_company_id 	int,
CONSTRAINT PK_CUST_ADDL_INFO PRIMARY KEY (id));

create table CUST_FINANCIAL_INFO(id     number(13,0),
cust_id     number(13,0) not null,
record_status     varchar2(1) default on null 'A' not null,
created_date     date default on null      sysdate not null,
last_updated_date     date default on null      sysdate not null,
created_by     varchar2(30),
last_updated_by     varchar2(30),
credit_in_other_bank     varchar2(1),
spouse_credit_in_other_bank     varchar2(1),
s37_data     varchar2(255),
cust_income     number(13,2),
life_insu_company_name     varchar2(50),
insu_term     varchar2(10),
insu_term_fee     number(13,2),
insu_term_other     varchar2(10),
payment_amount_at_bank     number(13,2),
account_number_at_bank     varchar2(50),
bank_name     varchar2(50),
bank_branch     varchar2(100),
avg_account_bal     number(13,2),
avg_electric_bill     number(13,2),
CONSTRAINT PK_CUST_FINANCIAL_INFO PRIMARY KEY (id));

create table CUST_CONTACT_INFO(id 	number(13,0),
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
email 	varchar2(100),
mobile 	varchar2(50) not null,
permanent_addr 	varchar2(255),
permanent_district 	int,
permanent_province 	int,
permanent_ward 	int,
spouse_addr 	varchar2(255),
spouse_district 	int,
spouse_province 	int,
spouse_ward 	int,
temp_addr 	varchar2(255),
temp_district 	int,
temp_province 	int,
temp_ward 	int,
current_addr_spouse 	varchar2(1),
CONSTRAINT PK_CUST_CONTACT_INFO PRIMARY KEY (id));

create table CUST_COMPANY_INFO(id 	int,
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
comp_addr_street 	varchar2(255),
comp_addr_province 	int,
comp_addr_district 	int,
comp_addr_ward 	int,
comp_name 	varchar2(255) not null,
comp_tax_number 	varchar2(50),
office_phone_number 	varchar2(50),
CONSTRAINT PK_CUST_COMPANY_INFO PRIMARY KEY (id));

create table CUST_ACCOUNT_LINK(id 	number(13,0),
cust_id 	number(13,0) default on null  	0 not null,
link_type 	varchar2(1) default on null 'A' not null,
link_seq 	int default on null  	1 not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
link_value 	varchar2(30) not null,
link_name 	varchar2(100),
link_system 	varchar2(3) not null,
link_currency 	varchar2(3) default on null 'VND',
link_product 	varchar2(10),
accounting_code 	varchar2(20),
CONSTRAINT PK_CUST_ACCOUNT_LINK PRIMARY KEY (id));

create table CUST_IDENTITY(id 	number(13,0),
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
identity_number 	varchar2(30) not null,
identity_issue_date 	date,
identity_issue_place 	varchar2(50),
identity_expiry_date 	date,
identity_type_id 	int not null,
CONSTRAINT PK_CUST_IDENTITY PRIMARY KEY (id));

create table CREDIT_APP_REQUEST(id 	number(15,0),
cust_id 	number(13,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
rate_index 	int,
int_rate 	number(13,5) not null,
ln_amount 	number(13,2) not null,
ln_amount_minus_insu 	number(13,2),
ln_end_date 	date,
ln_purpose 	int,
ln_other_purpose 	varchar2(100),
ln_start_date 	date,
ln_tenor 	int not null,
payment_date 	date,
sale_id 	int,
product_id 	int not null,
trans_office_id 	int,
contract_date 	date,
apply_to_object 	int,
has_insurance 	varchar2(1),
insu_amount 	number(13,2),
insu_company 	varchar2(10),
insu_staffId 	varchar2(100),
insu_fee 	number(13,2),
insu_type 	int,
insu_rate 	number(13,2),
mc_contract_number 	varchar2(20),
status 	varchar2(1),
disbursement_channel 	int,
disbursement_method 	int,
is_duplicated 	varchar2(1),
duplicated_note 	varchar2(2000),
scope 	int,
CONSTRAINT PK_CREDIT_APP_REQUEST PRIMARY KEY (id));

create table CREDIT_APP_LMS(id 	number(15,0),
credit_app_id 	number(15,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
core_ln_app_id 	varchar2(20),
disbursement_date 	date,
disbursement_status 	int,
first_payment_date 	date,
last_payment_date 	date,
disbursement_amount 	number(13,2),
CONSTRAINT PK_CREDIT_APP_LMS PRIMARY KEY (id));

create table CREDIT_APP_APPRAISAL(id 	number(15,0),
credit_app_id 	number(15,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
approved_amount 	number(13,2) not null,
approved_date 	date not null,
approved_user 	int not null,
industry	int,
CONSTRAINT PK_CREDIT_APP_APPRAISAL PRIMARY KEY (id));

create table CREDIT_APP_BPM(id 	number(15,0),
credit_app_id 	number(15,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
bpm_id 	number(15,0) not null,
bpm_app_id 	varchar2(32) not null,
bpm_app_number 	number(10,0) not null,
CONSTRAINT PK_CREDIT_APP_BPM PRIMARY KEY (id));

create table CREDIT_APP_TRAIL(id 	number(15,0),
credit_app_id 	number(15,0) not null,
trail_seq 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
step 	int,
task_id 	varchar2(32),
from_user 	int,
to_user 	int,
to_team 	int,
action 	int,
reason_id 	int,
user_comment 	varchar2(4000),
CONSTRAINT PK_CREDIT_APP_TRAIL PRIMARY KEY (id));

create table CREDIT_APP_COMMODITIES(id 	number(15,0),
credit_app_id 	number(15,0) not null,
comm_seq 	int not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
comm_id 	int not null,
frame_number 	varchar2(30),
price 	number(13,2),
serial_number 	varchar2(30),
model 	varchar2(50),
sip_id 	int,
advance_amount 	number(13,2),
discount_rate 	number(13,5),
CONSTRAINT PK_CREDIT_APP_COMMODITIES PRIMARY KEY (id));

create table COMM_BRAND(record_status     varchar2(1) default on null 'A' not null,
brand_id     int not null,
comm_id     int not null,
CONSTRAINT PK_COMM_BRAND PRIMARY KEY (brand_id,comm_id));

create table CODE_TABLE(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
parent_id 	int,
product_cat_id 	int default on null  	0,
product_group_id 	int default on null  	0,
product_id 	int default on null  	0,
code_group 	varchar2(5) not null,
category 	varchar2(10) not null,
code_value1 	varchar2(30),
code_value2 	varchar2(50),
code_message_key 	varchar2 (100),
description1 	varchar2(200),
description2 	varchar2(200),
status 	varchar2(1) default on null 'A',
reference 	varchar2(100),
CONSTRAINT PK_CODE_TABLE PRIMARY KEY (id));

create table USERS(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
login_id 	varchar2(30) not null,
manager_id 	int,
usr_full_name 	varchar2(100),
usr_type 	varchar2(1) not null,
usr_group 	varchar2(20) not null,
sale_code 	varchar2(50),
mobile 	varchar2(50),
sale_network_id 	int,
status 	varchar2(1),
start_eff_date 	date not null,
end_eff_date 	date default on null  	to_date('31-DEC-9999') not null,
CONSTRAINT PK_USERS PRIMARY KEY (id));

create table FUNCTIONS(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
module 	varchar2 (4),
function_code 	varchar2 (10) not null,
description 	varchar2 (100),
menu_id 	int not null,
page_file 	varchar2 (32),
page_access_right 	varchar2 (20) default on null 'NNNNYNNNN' not null,
url 	varchar2 (105),
status 	varchar2 (1),
CONSTRAINT PK_FUNCTIONS PRIMARY KEY (id));

create table SERVICES(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
module 	varchar2 (4),
service_name 	varchar2 (40) not null,
description 	varchar2 (100),
service_access_right 	varchar2 (1) default on null 'Y' not null,
service_path 	varchar2 (105),
posting_group 	varchar2(3),
status 	varchar2 (1),
CONSTRAINT PK_SERVICES PRIMARY KEY (id));

create table FIELDS(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
function_id 	int not null,
service_id 	int not null,
field_message_key 	varchar2(100),
field_name 	varchar2(100),
field_ui_id 	varchar2(50),
field_object_id 	varchar2(50),
field_access_right 	varchar2 (20) default on null 'NNNNYNNNN' not null,
status 	varchar2 (1),
CONSTRAINT PK_FIELDS PRIMARY KEY (id));

create table MENU(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
module 	varchar2 (4),
menu_code 	varchar2 (10) not null,
menu_title 	varchar2 (100),
menu_message_key 	varchar2 (100),
parent_menu 	varchar2 (10),
status 	varchar2 (1),
CONSTRAINT PK_MENU PRIMARY KEY (id));

create table ROLES(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
role_code 	varchar2 (10) not null,
role_type 	varchar2 (1),
role_name 	varchar2 (100),
status 	varchar2 (1),
CONSTRAINT PK_ROLES PRIMARY KEY (id));

create table ROLE_DETAILS(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
object_type 	varchar2(1) not null,
role_id 	int not null,
object_id 	int not null,
access_right 	varchar2 (20) default on null 'NNNNYNNNN' not null,
status 	varchar2 (1),
CONSTRAINT PK_ROLE_DETAILS PRIMARY KEY (id));

create table USERS_ROLE_MAPPING(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
user_id 	int not null,
object_type 	varchar2(1) not null,
object_id 	int not null,
access_right 	varchar2 (20) default on null 'NNNNYNNNN' not null,
status 	varchar2 (1),
CONSTRAINT PK_USERS_ROLE_MAPPING PRIMARY KEY (id));

create table USERS_SESSION(id 	int,
login_id 	varchar2(30) not null,
session_key 	varchar2(50),
channel_id 	int,
partner_id 	int,
last_update_date 	date default on null  	sysdate not null,
service_name 	varchar2(50),
function_code 	varchar2 (10),
CONSTRAINT PK_USERS_SESSION PRIMARY KEY (id));

create table PRODUCTS(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
product_category_id 	int,
product_group_id 	int not null,
product_code 	varchar2(10) not null,
product_name 	varchar2(100),
ccy 	varchar2(3) default on null 'VND' not null,
pti 	number(13,5),
tenor 	int,
min_tenor 	int,
max_tenor 	int,
rate_index 	int,
late_rate_index 	int,
late_penalty_fee 	number(13,2),
pre_liquidation_fee 	number(13,2),
max_quantity_commodities 	int,
max_loan_amount 	number(13,2),
min_loan_amount 	number(13,2),
status 	varchar2(1),
start_eff_date 	date not null,
end_eff_date 	date default on null  	to_date('31-DEC-9999') not null,
CONSTRAINT PK_PRODUCTS PRIMARY KEY (id));

create table INTEREST_TABLE(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
rate_type 	varchar2(1) default on null 'F' not null,
rate_code 	varchar2(10) not null,
rate_name 	varchar2(100),
monthly_rate 	number(13,5),
yearly_rate 	number(13,5),
spread 	number(13,5),
max_rate 	number(13,5),
min_rate 	number(13,5),
status 	varchar2(1),
start_eff_date 	date not null,
end_eff_date 	date default on null  	to_date('31-DEC-9999') not null,
CONSTRAINT PK_INTEREST_TABLE PRIMARY KEY (id));

create table GLOBAL_CHECKLIST(id 	int,
checklist_category 	varchar2(1) not null,
checklist_category_id 	int not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
checklist_name 	varchar2(100),
status 	varchar2(1),
start_eff_date 	date not null,
end_eff_date 	date default on null  	to_date('31-DEC-9999') not null,
CONSTRAINT PK_GLOBAL_CHECKLIST PRIMARY KEY (id));

create table PRODUCT_CHECKLIST_DOCUMENT(id     int,
global_checklist_id     int not null,
product_id     int not null,
document_id     int not null,
record_status     varchar2(1) default on null 'A' not null,
created_date     date default on null      sysdate not null,
last_updated_date     date default on null      sysdate not null,
created_by     varchar2(30),
last_updated_by     varchar2(30),
mandatory     varchar2(1) not null,
document_originality     varchar2(1) not null,
step     int,
is_lodge_require     varchar2(1),
allow_temp_uplift     varchar2(1),
document_code     varchar2(20),
CONSTRAINT PK_PRODUCT_CHECKLIST_DOCUMENT PRIMARY KEY (id));

create table CREDIT_APP_CHECKLIST_DOCUMENT(id 	number(15,0),
credit_app_id 	number(15,0) not null,
product_checklist_id 	int not null,
document_id 	int not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
is_mandatory 	varchar2(1) not null,
is_required 	varchar2(1) not null,
document_originality 	varchar2(1) not null,
step 	int,
is_lodge_require 	varchar2(1),
allow_temp_uplift 	varchar2(1),
is_lodged 	varchar2(1),
document_code 	varchar2(20),
document_bar_code 	varchar2(30),
CONSTRAINT PK_CREDIT_APP_CHECKLIST_DOCUMENT PRIMARY KEY (id));

create table GLOBAL_DOCUMENT(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
document_originality 	varchar2(1) not null,
document_name 	varchar2(100),
step 	int,
is_lodge_require 	varchar2(1),
allow_temp_uplift 	varchar2(1),
CONSTRAINT PK_GLOBAL_DOCUMENT PRIMARY KEY (id));

create table POSTING_CONFIGURATION(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
posting_group 	varchar2(3) not null,
posting_order 	int default on null  	1 not null,
transaction_type 	varchar2(10) not null,
debit_owner 	varchar2(1) default on null 'C' not null,
debit_branch 	varchar2(10) not null,
debit_ccy 	varchar2(3) default on null 'VND' not null,
debit_account 	varchar2(20) not null,
credit_owner 	varchar2(1) default on null 'C' not null,
credit_branch 	varchar2(10) not null,
credit_ccy 	varchar2(3) default on null 'VND' not null,
credit_account 	varchar2(20) not null,
amount 	number(13,2),
amount_tag 	varchar2(20) not null,
CONSTRAINT PK_POSTING_CONFIGURATION PRIMARY KEY (id));

create table POSTING_INSTANCE(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
posting_group 	varchar2(3) not null,
posting_order 	int default on null  	1 not null,
transaction_type 	varchar2(10) not null,
debit_owner 	varchar2(1) default on null 'C' not null,
debit_branch 	varchar2(10) not null,
debit_ccy 	varchar2(3) default on null 'VND' not null,
debit_account 	varchar2(20) not null,
credit_owner 	varchar2(1) default on null 'C' not null,
credit_branch 	varchar2(10) not null,
credit_ccy 	varchar2(3) default on null 'VND' not null,
credit_account 	varchar2(20) not null,
amount 	number(13,2),
CONSTRAINT PK_POSTING_INSTANCE PRIMARY KEY (id));

create table SCHEDULER(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
schedule_group 	varchar2(3) not null,
sch_name 	varchar2(50),
frequency 	varchar2(1) not null,
interval 	int not null,
start_time 	date not null,
next_schedule_time 	date,
status 	varchar2(1) default on null 'S' not null,
num_of_run 	int default on null  	0,
request 	varchar2(255),
allow_overlap 	varchar2(1) default on null 'N' not null,
CONSTRAINT PK_SCHEDULER PRIMARY KEY (id));

create table SCHEDULE_INSTANCE(id 	number(17,0),
schedule_id 	int not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
start_time 	date not null,
end_time 	date,
status 	varchar2(1),
response_code 	varchar2(10),
message 	varchar2(255),
CONSTRAINT PK_SCHEDULE_INSTANCE PRIMARY KEY (id));

create table PARTNER(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
partner_code 	varchar2(10),
partner_name 	varchar2(100),
partner_acct_in_corebank 	varchar2(30),
status 	varchar2(1),
CONSTRAINT PK_PARTNER PRIMARY KEY (id));

create table CREDIT_APP_ADDITIONAL(id 	number(15,0),
credit_app_id 	number(15,0) not null,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
card_holder_name 	varchar2(100),
is_IB_allowed 	varchar2(1),
receive_card_addr 	int,
issue_fee_coll 	varchar2(1),
difference_issue_fee 	number(13,2),
annual_fee_coll 	varchar2(1),
annual_fee_frequency 	int,
difference_annual_fee 	number(13,2),
insu_fee_coll 	varchar2(1),
insu_fee_frequency 	int,
difference_insu_fee 	number(13,2),
CONSTRAINT PK_CREDIT_APP_ADDITIONAL PRIMARY KEY (id));

create table PARAMETERS(param_name 	varchar2(20),
param_value 	varchar2 (50) not null,
param_data_type 	varchar2(1) not null,
param_description 	varchar2(100),
status 	varchar2(1) default on null 'A' not null,
CONSTRAINT PK_PARAMETERS PRIMARY KEY (param_name));

create table UPL_CORE_CONTRACT(id 	int,
upl_master_id 	int,
SEL_DATE 	date,
CONTRACT_REF 	varchar2(20),
LD_ID 	varchar2(20),
CUS 	varchar2(20),
NAME 	varchar2(50),
SUB_PRODUCT 	varchar2(10),
RATE 	number(13,5),
TERM 	int,
CURR 	varchar2(3),
AMT 	number(13,2),
ISS_AMT 	number(13,2),
CONTRACT_DATE 	date,
VAL_DATE 	date,
MAT_DATE_BD 	date,
AGREE_DATE 	date,
MATDATE_TH 	date,
AMT_CL 	number(13,2),
STATUS 	varchar2(20),
PARNER 	varchar2(20),
STATUS_LD 	varchar2(20),
CONSTRAINT PK_UPL_CORE_CONTRACT PRIMARY KEY (id));

create table UPL_CC_STATEMENT(id 	int,
upl_master_id 	int,
CARD_ID 	varchar2(10),
HANG_THE 	varchar2(10),
LOAI_THE 	varchar2(20),
NGAY_KICH_HOAT_THE 	Date,
REPORT_DATE 	Date,
CONTRACT_NUMBER 	varchar2(20),
CARDHOLDER_NAME 	varchar2(50),
CLIENT_NUMBER 	varchar2(20),
CONTRACT_STATUS 	varchar2(50),
CONTRACT_STATUS_CODE 	varchar2(5),
SCHEME_CODE 	varchar2(20),
SCHEME_NAME 	varchar2(50),
CARD_NUMBER 	varchar2(20),
CARD_STATUS 	varchar2(50),
CARD_STATUS_CODE 	varchar2(5),
MA_CN 	varchar2(5),
TEN_CN 	varchar2(50),
NGAY_MO_THE 	Date,
CARD_EXPIRE 	Date,
NGAY_DONG_THE 	Date,
CREDIT_LIMIT 	number(13,2),
HAN_MUC_CON_LAI 	number(13,2),
LAI_SUAT_THONG_THUONG 	number(13,5),
DU_NO_THOI_DIEM_BC 	number(13,2),
DU_NO_DEN_HAN_TT 	number(13,2),
DU_NO_CHUA_DEN_HAN_TT 	number(13,2),
SO_TIEN_CAN_TT_TOI_THIEU 	number(13,2),
TT_DU_MIN 	varchar2(20),
SO_TIEN_MIN_CON_LAI 	number(13,2),
GOC_TAI_THOI_DIEM_BC 	number(13,2),
LAI_TRONG_HAN 	number(13,2),
LAI_PHAT 	number(13,2),
TONG_PHI 	number(13,2),
GOC_QUA_HAN_TAI_THOI_DIEM_BC 	number(13,2),
TONG_PHI_DEN_HAN_TT 	number(13,2),
GOC_CHUA_DEN_HAN_TT 	number(13,2),
LAI_TRONG_HAN_CHUA_DEN_HAN_TT 	number(13,2),
LAI_PHAT_CHUA_DEN_HAN_TT 	number(13,2),
TONG_PHI_CHUA_DEN_HAN_TT 	number(13,2),
SO_NGAY_QUA_HAN_TREN_WAY4 	int,
NHOM_NO_WAY4 	varchar2(3),
SO_DIEM_LOYALTY_DAUKY 	int,
SO_DIEM_LOYALTY_TICH_LUY_TK 	int,
SO_DIEM_LOYALTY_QUY_DOI_TK 	int,
SO_DIEM_LOYALTY_CUOI_KY 	int,
CONSTRAINT PK_UPL_CC_STATEMENT PRIMARY KEY (id));

create table UPL_MASTER(id     int,
record_status     varchar2(1) default on null 'A' not null,
created_date     date default on null      sysdate not null,
last_updated_date     date default on null      sysdate not null,
created_by     varchar2(30),
last_updated_by     varchar2(30),
upl_format     varchar2(5) not null,
from_source     int not null,
upl_code     varchar2(30) not null,
upl_type     int,
owner_id     int,
imported     int default on null      0,
total_allocated     int default on null      0,
CONSTRAINT PK_UPL_MASTER PRIMARY KEY (id));

create table UPL_DETAIL(id     int,
upl_master_id     int,
upl_seq     int default on null      1 not null,
imported     int default on null      0,
total_allocated     int default on null      0,
upl_file_name     varchar2(100),
server_file_name     varchar2(50),
status     varchar2(1) default on null 'N',
CONSTRAINT PK_UPL_DETAIL PRIMARY KEY (id));

create table UPL_CUSTOMER(id     number(18,0),
upl_detail_id     int,
customer_name     varchar2(50),
birth_date     varchar2(15),
mobile     varchar2(15),
identity_number     varchar2(15),
address     varchar2(100),
income     varchar2(15),
note     varchar2(100),
response_code     varchar2(10),
message     varchar2(200),
CONSTRAINT PK_UPL_CUSTOMER PRIMARY KEY (id));

create table ALLOCATION_MASTER(id 	int,
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
upl_master_id 	int not null,
allocated_seq 	int not null,
allocated_number 	int,
allocated_to 	int not null,
allocated_type 	varchar2(1) not null,
related_allocation 	int default on null  	0,
CONSTRAINT PK_ALLOCATION_MASTER PRIMARY KEY (id));

create table ALLOCATION_DETAIL(id 	number(15,0),
allocation_master_id 	int not null,
upl_detail_id 	int not null,
allocated_number 	int,
object_type 	varchar2(1),
object_id 	int not null,
upl_customer_id 	number(18,0) default on null  	0,
status 	varchar2(1) default on null 'F' not null,
CONSTRAINT PK_ALLOCATION_DETAIL PRIMARY KEY (id));

create table CUST_PROSPECT(id 	number(15,0),
record_status 	varchar2(1) default on null 'A' not null,
created_date 	date default on null  	sysdate not null,
last_updated_date 	date default on null  	sysdate not null,
created_by 	varchar2(30),
last_updated_by 	varchar2(30),
allocation_detail_id 	number(15,0),
upl_customer_id 	number(18,0),
cust_name 	varchar2(100),
identity_number 	varchar2(15),
mobile 	varchar2(15),
gender 	int,
birth_date 	date,
professional 	int,
accommodation_type 	int,
permanent_addr 	varchar2(100),
permanent_province 	int,
permanent_district 	int,
permanent_ward 	int,
comp_addr_street 	varchar2(100),
comp_addr_province 	int,
comp_addr_district 	int,
comp_addr_ward 	int,
cust_income 	number(13,2),
note 	varchar2(100),
CONSTRAINT PK_CUST_PROSPECT PRIMARY KEY (id));

create table CALL_RESULT(id 	number(13,0),
allocation_detail_id 	number(15,0),
cust_prospect_id 	number(15,0),
call_times 	int default on null  	1 not null,
call_status 	int not null,
call_result 	int not null,
next_action 	int,
next_action_date 	date,
call_date 	date default on null  	sysdate,
note 	varchar2(200),
CONSTRAINT PK_CALL_RESULT PRIMARY KEY (id));

create table TEAMS(id     int,
record_status     varchar2(1) default on null 'A' not null,
created_date     date default on null      sysdate not null,
last_updated_date     date default on null      sysdate not null,
created_by     varchar2(30),
last_updated_by     varchar2(30),
manager_id     int not null,
team_type     varchar2(1) not null,
team_group     varchar2(20) not null,
team_code     varchar2 (10) not null,
team_name     varchar2 (100),
status     varchar2 (1),
CONSTRAINT PK_TEAMS PRIMARY KEY (id));

create table TEAM_MEMBER(id     int,
team_id     int not null,
user_id     int not null,
status     varchar2 (1),
CONSTRAINT PK_TEAM_MEMBER PRIMARY KEY (id));

