<<<<<<< HEAD
﻿-- MCPORTAL_DATA
-- MCPORTAL_INDEX
-- MCPORTAL_LOB

CREATE UNIQUE INDEX UNI1_CODE_TABLE ON 
	CODE_TABLE (CATEGORY,CODE_VALUE1,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID) TABLESPACE MCPORTAL_INDEX;

=======
﻿-- MCPORTAL_DATA
-- MCPORTAL_INDEX
-- MCPORTAL_LOB

CREATE UNIQUE INDEX UNI1_CODE_TABLE ON 
	CODE_TABLE (CATEGORY,CODE_VALUE1,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID) TABLESPACE MCPORTAL_INDEX;

>>>>>>> ed04cdb86e7cddb8374d9d8eba6edaea2087e301
