-- * PRODUCTS
-- Them kenh ban CD, TW
INSERT INTO CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
				values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,sysdate, 0, 0, 0, 'PROD','CHANNEL','CD','CD','A');
INSERT INTO CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,DESCRIPTION1,STATUS)
				values(SEQ_CODE_TABLE_ID.nextval,'A', sysdate,sysdate, 0, 0, 0, 'PROD','CHANNEL','TW','TW','A');
-- insert url type : goods
Insert into CODE_TABLE (SEQ_CODE_TABLE_ID.nextval,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE,START_EFF_DATE,END_EFF_DATE) values ('4895114','A',to_date('24-07-2019','DD-MM-RRRR'),to_date('24-07-2019','DD-MM-RRRR'),null,null,'13082','0','0','0','MISC','UPL_TYPE','GOODS',null,null,'Upload goods, brand, model',null,'A',null,to_date('24-07-2019','DD-MM-RRRR'),to_date('31-12-9999','DD-MM-RRRR'));
-- Them paramneter duong dan file : 
Insert into parameters (PARAM_NAME,PARAM_VALUE,PARAM_DATA_TYPE,PARAM_DESCRIPTION,STATUS) values ('FILE_DIRECTORY_PROD','/opt/tomcat/webapps/upload/','S','Thư muc chua files upload cua product_manager /opt/tomcat/webapps/upload/','A');
-- them moi nhom san pham 
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('04-06-2019','DD-MM-RRRR'),to_date('04-06-2019','DD-MM-RRRR'),null,null,null,'0','0','0','PR','SC_GROUP','HT',null,null,'High Tech',null,'A',null);
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('04-06-2019','DD-MM-RRRR'),to_date('04-06-2019','DD-MM-RRRR'),null,null,null,'0','0','0','PR','SC_GROUP','NHT',null,null,'Non High Tech',null,'A',null);
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('04-06-2019','DD-MM-RRRR'),to_date('04-06-2019','DD-MM-RRRR'),null,null,null,'0','0','0','PR','SC_GROUP','ALL',null,null,'All',null,'A',null);
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('04-06-2019','DD-MM-RRRR'),to_date('04-06-2019','DD-MM-RRRR'),null,null,null,'0','0','0','PR','SC_GROUP','OTHER',null,null,'Other',null,'A',null);
-- Them moi nhom san pham TW
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('14-06-2019','DD-MM-RRRR'),to_date('14-06-2019','DD-MM-RRRR'),null,null,null,'1','0','0','INST','COMM','TW_XM',null,null,'Xe máy',null,'A',null);
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('14-06-2019','DD-MM-RRRR'),to_date('14-06-2019','DD-MM-RRRR'),null,null,null,'1','0','0','INST','COMM','TW_XDD',null,null,'xe đap điện',null,'A',null);
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('14-06-2019','DD-MM-RRRR'),to_date('14-06-2019','DD-MM-RRRR'),null,null,null,'1','0','0','INST','COMM','TW_XMD',null,null,'Xe máy điện',null,'A',null);
-- Gan nhom san pham TW voi nhom TW
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) 
values (MAPPING_HIERARCHY_SEQ.nextval,(select id from code_table where category='COMM' and code_value1 ='TW_XM'),(select ID from code_table where category='CHANNEL' and  code_value1 like 'TW'),null,'MAP_COMM_CHANNEL',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) 
values (MAPPING_HIERARCHY_SEQ.nextval,(select id from code_table where category='COMM' and code_value1 ='TW_XDD'),(select ID from code_table where category='CHANNEL' and  code_value1 like 'TW'),null,'MAP_COMM_CHANNEL',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) 
values (MAPPING_HIERARCHY_SEQ.nextval,(select id from code_table where category='COMM' and code_value1 ='TW_XMD'),(select ID from code_table where category='CHANNEL' and  code_value1 like 'TW'),null,'MAP_COMM_CHANNEL',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');

-- Them moi nhom Action 
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('17-06-2019','DD-MM-RRRR'),to_date('17-06-2019','DD-MM-RRRR'),null,null,null,'0','0','0','STAT','DATA_CHANGE_ACTION','N',null,null,'Create new',null,'A',null);
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('17-06-2019','DD-MM-RRRR'),to_date('17-06-2019','DD-MM-RRRR'),null,null,null,'0','0','0','STAT','DATA_CHANGE_ACTION','U',null,null,'Update',null,'A',null);
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('17-06-2019','DD-MM-RRRR'),to_date('17-06-2019','DD-MM-RRRR'),null,null,null,'0','0','0','STAT','DATA_CHANGE_ACTION','A',null,null,'Activate',null,'A',null);
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('17-06-2019','DD-MM-RRRR'),to_date('17-06-2019','DD-MM-RRRR'),null,null,null,'0','0','0','STAT','DATA_CHANGE_ACTION','I',null,null,'De-activate',null,'A',null);
Insert into CODE_TABLE (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,PARENT_ID,PRODUCT_CAT_ID,PRODUCT_GROUP_ID,PRODUCT_ID,CODE_GROUP,CATEGORY,CODE_VALUE1,CODE_VALUE2,CODE_MESSAGE_KEY,DESCRIPTION1,DESCRIPTION2,STATUS,REFERENCE) values (SEQ_CODE_TABLE_ID.nextval,'A',to_date('17-06-2019','DD-MM-RRRR'),to_date('17-06-2019','DD-MM-RRRR'),null,null,null,'0','0','0','STAT','DATA_CHANGE_ACTION','D',null,null,'Delete',null,'A',null);

-- Them moi mapping cac loai hang hoa dac biet TW
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) 
values (MAPPING_HIERARCHY_SEQ.nextval,'52','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');


-- Tao moi bang mapping 
  CREATE TABLE "SIT_MCP"."MAPPING_HIERARCHY" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"MAP_ID1" NUMBER(*,0) NOT NULL ENABLE, 
	"MAP_ID2" NUMBER(*,0) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER(*,0), 
	"MAP_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1 BYTE), 
	"RECORD_STATUS" VARCHAR2(1 BYTE), 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(20 BYTE), 
	 CONSTRAINT "MAPPING_HIERARCHY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MCPORTAL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MCPORTAL_DATA" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SIT_MCP"."TRG_MAPPING_HIERARCHY_AUDIT" 
BEFORE INSERT OR UPDATE ON MAPPING_HIERARCHY             FOR EACH ROW
DECLARE
    l_json varchar2(32000);
    l_seq int;
    l_actionid int;
BEGIN

IF :new.ID is null THEN
select MAPPING_HIERARCHY_SEQ.nextval into :new.ID from dual;
END IF;

SELECT JSON_OBJECT ('ID' VALUE :NEW.ID, 'MAP_ID1' VALUE :NEW.MAP_ID1, 'MAP_ID2' VALUE :NEW.MAP_ID2, 'PARENT_ID' VALUE :NEW.PARENT_ID, 'MAP_TYPE' VALUE :NEW.MAP_TYPE, 'STATUS' VALUE :NEW.STATUS, 'RECORD_STATUS' VALUE :NEW.RECORD_STATUS, 'CREATED_DATE' VALUE :NEW.CREATED_DATE, 'CREATED_BY' VALUE :NEW.CREATED_BY, 'LAST_UPDATED_DATE' VALUE :NEW.LAST_UPDATED_DATE, 'LAST_UPDATED_BY' VALUE :NEW.LAST_UPDATED_BY) into l_json from dual;

select nvl(max(CHANGE_SEQ),0) + 1 into l_seq 
from AUDIT_DATA_CHANGE where TABLE_NAME = 'MAPPING_HIERARCHY' and MASTER_KEY = :NEW.ID;

if INSERTING then
    select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'N';
else
    select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'U';
    if :OLD.STATUS <> :NEW.STATUS then
        if :NEW.STATUS = 'A' then
            select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'A';
        else
            select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'I';
        end if;
    end if;
end if;

insert into AUDIT_DATA_CHANGE(LAST_UPDATED_BY,TABLE_NAME,MASTER_KEY,REFERENCE_KEY,CHANGE_SEQ,ACTION,CONTENT) 
values(nvl(:NEW.LAST_UPDATED_BY,:NEW.CREATED_BY),'MAPPING_HIERARCHY',:NEW.ID,:NEW.PARENT_ID,l_seq,l_actionid,l_json);

END;
/
ALTER TRIGGER "SIT_MCP"."TRG_MAPPING_HIERARCHY_AUDIT" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SIT_MCP"."MAPPING_HIERARCHY_TRG" 
BEFORE INSERT ON MAPPING_HIERARCHY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MAPPING_HIERARCHY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SIT_MCP"."MAPPING_HIERARCHY_TRG" ENABLE;


-- Tao sequend cho bang mapping 
CREATE SEQUENCE MAPPING_HIERARCHY_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

-- Tao trigger
create or replace TRIGGER TRG_MAPPING_HIERARCHY_AUDIT 
BEFORE INSERT OR UPDATE ON MAPPING_HIERARCHY             FOR EACH ROW
DECLARE
    l_json varchar2(32000);
    l_seq int;
    l_actionid int;
BEGIN

IF :new.ID is null THEN
select MAPPING_HIERARCHY_SEQ.nextval into :new.ID from dual;
END IF;

SELECT JSON_OBJECT ('ID' VALUE :NEW.ID, 'MAP_ID1' VALUE :NEW.MAP_ID1, 'MAP_ID2' VALUE :NEW.MAP_ID2, 'PARENT_ID' VALUE :NEW.PARENT_ID, 'MAP_TYPE' VALUE :NEW.MAP_TYPE, 'STATUS' VALUE :NEW.STATUS, 'RECORD_STATUS' VALUE :NEW.RECORD_STATUS, 'CREATED_DATE' VALUE :NEW.CREATED_DATE, 'CREATED_BY' VALUE :NEW.CREATED_BY, 'LAST_UPDATED_DATE' VALUE :NEW.LAST_UPDATED_DATE, 'LAST_UPDATED_BY' VALUE :NEW.LAST_UPDATED_BY) into l_json from dual;

select nvl(max(CHANGE_SEQ),0) + 1 into l_seq 
from AUDIT_DATA_CHANGE where TABLE_NAME = 'MAPPING_HIERARCHY' and MASTER_KEY = :NEW.ID;

if INSERTING then
    select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'N';
else
    select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'U';
    if :OLD.STATUS <> :NEW.STATUS then
        if :NEW.STATUS = 'A' then
            select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'A';
        else
            select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'I';
        end if;
    end if;
end if;

insert into AUDIT_DATA_CHANGE(LAST_UPDATED_BY,TABLE_NAME,MASTER_KEY,REFERENCE_KEY,CHANGE_SEQ,ACTION,CONTENT) 
values(nvl(:NEW.LAST_UPDATED_BY,:NEW.CREATED_BY),'MAPPING_HIERARCHY',:NEW.ID,:NEW.PARENT_ID,l_seq,l_actionid,l_json);

END;
 
-- Tao moi user 
-- Nguyen Tien Manh
Insert into USERS (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,LOGIN_ID,EMP_ID,USR_FULL_NAME,USR_TYPE,STATUS,START_EFF_DATE,END_EFF_DATE) 
values (SEQ_USERS_ID.NEXTVAL,'A',sysdate,null,'manhnt1.ho',null,'manhnt1.ho',null,'Nguyen Tien Manh',null,'A',sysdate,to_date('31-12-9999', 'DD/MM/YY'));

Insert into USERS_ROLE_MAPPING (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,USER_ID,OBJECT_TYPE,OBJECT_ID,ACCESS_RIGHT,STATUS) 
	values (null,'A',sysdate,null,null,null,(Select ID from USERS where LOGIN_ID = 'manhnt1.ho'),'R',(select ID from ROLES where ROLE_CODE = 'PR_PTSP'),'NNNNYNNNN','A');

Insert into USERS_ROLE_MAPPING (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,USER_ID,OBJECT_TYPE,OBJECT_ID,ACCESS_RIGHT,STATUS) 
	values (null,'A',sysdate,null,null,null,(Select ID from USERS where LOGIN_ID = 'manhnt1.ho'),'R',(select ID from ROLES where ROLE_CODE = 'PR_SA'),'NNNNYNNNN','A');    
    
-- Tester 11 
Insert into USERS (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,LOGIN_ID,EMP_ID,USR_FULL_NAME,USR_TYPE,STATUS,START_EFF_DATE,END_EFF_DATE) 
values (SEQ_USERS_ID.NEXTVAL,'A',sysdate,null,'manhnt1.ho',null,'tester11',null,'Tester11',null,'A',sysdate,to_date('31-12-9999', 'DD/MM/YY'));

Insert into USERS_ROLE_MAPPING (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,USER_ID,OBJECT_TYPE,OBJECT_ID,ACCESS_RIGHT,STATUS) 
	values (null,'A',sysdate,null,null,null,(Select ID from USERS where LOGIN_ID = 'tester11'),'R',(select ID from ROLES where ROLE_CODE = 'PR_PTSP'),'NNNNYNNNN','A');

Insert into USERS_ROLE_MAPPING (ID,RECORD_STATUS,CREATED_DATE,LAST_UPDATED_DATE,CREATED_BY,LAST_UPDATED_BY,USER_ID,OBJECT_TYPE,OBJECT_ID,ACCESS_RIGHT,STATUS) 
	values (null,'A',sysdate,null,null,null,(Select ID from USERS where LOGIN_ID = 'tester11'),'R',(select ID from ROLES where ROLE_CODE = 'PR_SA'),'NNNNYNNNN','A');    


-- Them moi bang mapping 
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('24','3','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('25','5','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('26','31','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('27','30','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('28','49','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('29','65','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('30','65','98745',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('31','65','98746',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('32','114','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('33','114','98745',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('34','114','98746',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('35','115','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('36','115','98745',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('37','115','98746',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('38','66','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('39','66','98745',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('40','66','98746',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('41','143','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('42','69','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values ('43','33','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');
Insert into mapping_hierarchy (ID,MAP_ID1,MAP_ID2,PARENT_ID,MAP_TYPE,STATUS,RECORD_STATUS,CREATED_DATE,CREATED_BY,LAST_UPDATED_DATE,LAST_UPDATED_BY) values (MAPPING_HIERARCHY_SEQ.nextval,'52','98744',null,'MAP_SCHEME_COMM_TW',null,null,null,null,to_date('17-06-2019','DD-MM-RRRR'),'Admin');


-- chay lai trigger anh Quan
CREATE OR REPLACE TRIGGER TRG_CODE_TABLE_AUDIT 
BEFORE INSERT OR UPDATE ON CODE_TABLE             FOR EACH ROW
DECLARE
    l_json varchar2(32000);
    l_seq int;
    l_actionid int;
BEGIN

IF :new.ID is null THEN
select SEQ_CODE_TABLE_ID.nextval into :new.ID from dual;
END IF;

SELECT JSON_OBJECT ('START_EFF_DATE' VALUE :NEW.START_EFF_DATE, 'END_EFF_DATE' VALUE :NEW.END_EFF_DATE, 'ID' VALUE :NEW.ID, 'RECORD_STATUS' VALUE :NEW.RECORD_STATUS, 'CREATED_DATE' VALUE :NEW.CREATED_DATE, 'LAST_UPDATED_DATE' VALUE :NEW.LAST_UPDATED_DATE, 'CREATED_BY' VALUE :NEW.CREATED_BY, 'LAST_UPDATED_BY' VALUE :NEW.LAST_UPDATED_BY, 'PARENT_ID' VALUE :NEW.PARENT_ID, 'PRODUCT_CAT_ID' VALUE :NEW.PRODUCT_CAT_ID, 'PRODUCT_GROUP_ID' VALUE :NEW.PRODUCT_GROUP_ID, 'PRODUCT_ID' VALUE :NEW.PRODUCT_ID, 'CODE_GROUP' VALUE :NEW.CODE_GROUP, 'CATEGORY' VALUE :NEW.CATEGORY, 'CODE_VALUE1' VALUE :NEW.CODE_VALUE1, 'CODE_VALUE2' VALUE :NEW.CODE_VALUE2, 'CODE_MESSAGE_KEY' VALUE :NEW.CODE_MESSAGE_KEY, 'DESCRIPTION1' VALUE :NEW.DESCRIPTION1, 'DESCRIPTION2' VALUE :NEW.DESCRIPTION2, 'STATUS' VALUE :NEW.STATUS, 'REFERENCE' VALUE :NEW.REFERENCE) into l_json from dual;

select nvl(max(CHANGE_SEQ),0) + 1 into l_seq 
from AUDIT_DATA_CHANGE where TABLE_NAME = 'CODE_TABLE' and MASTER_KEY = :NEW.ID;

if INSERTING then
    --select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'N';
    select to_number(PARAM_VALUE) into l_actionid from PARAMETERS where PARAM_NAME = 'CT_DATA_CHANGE_ACTION_N';
else
    --select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'U';
    select to_number(PARAM_VALUE) into l_actionid from PARAMETERS where PARAM_NAME = 'CT_DATA_CHANGE_ACTION_U';
    if :OLD.STATUS <> :NEW.STATUS then
        if :NEW.STATUS = 'A' then
            --select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'A';
            select to_number(PARAM_VALUE) into l_actionid from PARAMETERS where PARAM_NAME = 'CT_DATA_CHANGE_ACTION_A';
        else
            --select ID into l_actionid from CODE_TABLE where CATEGORY = 'DATA_CHANGE_ACTION' and CODE_VALUE1 = 'I';
            select to_number(PARAM_VALUE) into l_actionid from PARAMETERS where PARAM_NAME = 'CT_DATA_CHANGE_ACTION_I';
        end if;
    end if;
end if;

insert into AUDIT_DATA_CHANGE(LAST_UPDATED_BY,TABLE_NAME,MASTER_KEY,REFERENCE_KEY,CHANGE_SEQ,ACTION,CONTENT) 
values(nvl(:NEW.LAST_UPDATED_BY,:NEW.CREATED_BY),'CODE_TABLE',:NEW.ID,:NEW.PARENT_ID,l_seq,l_actionid,l_json);

END;
/

-- tiep
insert into PARAMETERS(PARAM_NAME,PARAM_VALUE,PARAM_DATA_TYPE,PARAM_DESCRIPTION)
select 'CT_DATA_CHANGE_ACTION_'||code_value1,id,'I',description1 from code_table where category='DATA_CHANGE_ACTION';
commit;


