package com.mcredit.model.enums;

public enum CommonValidationLength {
	
	VAL_MESSAGELOG_ORDER_1(1),
	
	LEN_BPM_APP_ID(32),
	
	MAX_LEN_MESSAGETASK_STATUS(1),
	MAX_LEN_MESSAGETASK_TASKTYPE(1),
	MAX_LEN_MESSAGETASK_TRANSTYPE(20),
	MAX_LEN_MESSAGETASK_DTOOBJECT(4000),
	MAX_LEN_MESSAGETASK_RELATIONID(30),
	
	MAX_LEN_RATEINDEX(38),
	MAX_LEN_INTRATE(19),
	MAX_LEN_LNAMOUNT(13),
	MAX_LEN_RLNPURPOSE(18),
	MAX_LEN_LNOTHERPURPOSE(100),
	MAX_LEN_LNTENOR(38),
	MAX_LEN_GETSALEID(38),
	MAX_LEN_PRODUCTID(38),
	MAX_LEN_TRANSOFFICEID(38),
	MAX_LEN_APPLYTOOBJECT(38),
	MAX_LEN_HASINSURANCE(1),
	MAX_LEN_INSUAMOUNT(13),
	MAX_LEN_INSUCOMPANY(10),
	MAX_LEN_INSUSTAFFID(100),
	MAX_LEN_INSUFEE(13),
	MAX_LEN_INSUTYPE(38),
	MAX_LEN_INSURATE(13),
	MAX_LEN_MCCONTRACTNUMBER(20),
	MAX_LEN_GETSTATUS(1),
	MAX_LEN_DISBURSEMENTCHANNEL(38),
	MAX_LEN_DISBURSEMENTMETHOD(38),
	MAX_LEN_ISDUPLICATED(200),
	MAX_LEN_SCOPE(38),
	MAX_LEN_RECORDSTATUS(1),
	MAX_LEN_APPLMS_CORELNAPPID(20),
	MAX_LEN_DISBURSEMENTSTATUS(38),
	MAX_LEN_DISBURSEMENTAMOUNT(13);
	
	private final int value;

	CommonValidationLength(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}
    
}
