package com.mcredit.model.enums;

public enum CreditValidationLength {
	
	MAX_LEN_MESSAGELOG_MSGTYPE(1),
	MAX_LEN_MESSAGELOG_FROMCHANNEL(3),
	MAX_LEN_MESSAGELOG_TOCHANNEL(3),
	MAX_LEN_MESSAGELOG_RELATIONID(40),
	MAX_LEN_MESSAGELOG_TRANSTYPE(10),
	MAX_LEN_MESSAGELOG_TRANSID(17),
	MAX_LEN_MESSAGELOG_GETSERVICENAME(50),
	MAX_LEN_MESSAGELOG_MSGREQUEST(4000),
	MAX_LEN_MESSAGELOG_MSGRESPONSE(4000),
	MAX_LEN_MESSAGELOG_MSGORDER(2),
	MAX_LEN_MESSAGELOG_RESPONSECODE(10),
	MAX_LEN_MESSAGELOG_RESPONSEERRORDESC(255);
	
	private final int value;

	CreditValidationLength(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}
    
}
