package com.mcredit.model.enums;

public enum CTCodeValue1 {

    WH_NEW_DOCUMENT("WH_NEW_DOCUMENT"),
    WH_ALLOCATED_WAIT_CHECK("WH_ALLOCATED_WAIT_CHECK"),
    WH_NEW_WAIT_ALLOCATION("WH_NEW_WAIT_ALLOCATION"),
    WH_LODGED_RETURN("WH_LODGED_RETURN"),
    WH_APP_RE_BORROW("WH_APP_RE_BORROW"),
    WH_RETURN_DOC_NOT_RECEIVE("WH_RETURN_DOC_NOT_RECEIVE"),
    WH_COMPLETE_NOT_RECEIVE("WH_COMPLETE_NOT_RECEIVE"),
    WH_LODGED_COMPLETE_RETURN("WH_LODGED_COMPLETE_RETURN"),
    WH_LODGED_ERR_UPDATE_RETURN("WH_LODGED_ERR_UPDATE_RETURN"),
    WH_NOT_RECEIVE("WH_NOT_RECEIVE"),
    WH_LODGE_COMPLETE_BORROW("WH_LODGE_COMPLETE_BORROW"),
    WH_LODGED_ERR_UPDATE_BORROW("WH_LODGED_ERR_UPDATE_BORROW"),
    WH_LODGED_ERR_UPDATE("WH_LODGED_ERR_UPDATE"),
    WH_LODGED_COMPLETE("WH_LODGED_COMPLETE"),
    WH_NEW_WAIT("WH_NEW_WAIT"),
    WH_PAPER("WH_PAPER"),
    WH_WOOD("WH_WOOD"),
    WH_APP_CAVET_R("WH_APP_CAVET_R"),
    WH_METAL("WH_METAL"),
    WH_PLASTIC("WH_PLASTIC"),
    WH_LODGE_TMP("WH_LODGE_TMP"),
    WH_WAIT_ERR_UPDATE("WH_WAIT_ERR_UPDATE"),
    WH_WAIT_COMPLETE("WH_WAIT_COMPLETE"),
    WH_ERR("WH_ERR"),
    WH_STATUS_CHANGE("WH_STATUS_CHANGE"),
    WH_LOAN_DOC("WH_LOAN_DOC"),
    WH_CAVET("WH_CAVET"),
    WH_ERR_UPDATE("WH_ERR_UPDATE"),
    WH_THANKS_LETTER("WH_THANKS_LETTER"),
    WH_LOGDE("WH_LOGDE"),
    WH_SAVE_AND_MOVE("WH_SAVE_AND_MOVE"),
    WH_SEND_THANKLETTER("WH_SEND_THANKLETTER"),
    
    WAIT_SEND("WAIT_SEND"),
    SEND_OK("SEND_OK"),
    SEND_FAIL("SEND_FAIL"),
    WH_OP_2("WH_OP_2"),
    
    // Cavet type
    WH_PASS("WH_PASS"),
    WH_IN_CAVET("WH_IN_CAVET"),
    WH_IN_APPENDIX("WH_IN_APPENDIX"),
    WH_OK_RETURN("WH_OK_RETURN"),
    WH_RETURN("WH_RETURN"),
    WH_REJECT("WH_REJECT"),
    WH_OK("WH_OK"),
    WH_WAIT("WH_WAIT"),
    WH_RE_STATUS("WH_RE_STATUS"),
    WH_APR_STATUS("WH_APR_STATUS"),
    WH_REJECT_RETURN("WH_REJECT_RETURN"),
    //WH_BRW_TYPE("WH_BRW_TYPE"),
    WH_DONE("WH_DONE"),
    WH_DOC_TYPE_CHANGE("WH_DOC_TYPE_CHANGE"),
    WH_WAIT_RETURN("WH_WAIT_RETURN"),
    // Err type Cavet         
    WH_EXPIRED_30_DAYS("WH_EXPIRED_30_DAYS"),
    WH_EXPIRED_45_DAYS("WH_EXPIRED_45_DAYS"),
    WH_WRONG_CHASSIS("WH_WRONG_CHASSIS"),
    WH_WRONG_ENGINE("WH_WRONG_ENGINE"),
    WH_WRONG_BRAND("WH_WRONG_BRAND"),
    WH_WRONG_NAME("WH_WRONG_NAME"),
    WH_WRONG_TYPE_NUM("WH_WRONG_TYPE_NUM"),
    
    WH_STATUS_01("WH_STATUS_01"),
    WH_STATUS_02("WH_STATUS_02"),
    WH_STATUS_03("WH_STATUS_03"),
    WH_STATUS_04("WH_STATUS_04"),
    WH_STATUS_05("WH_STATUS_05"),
    WH_STATUS_06("WH_STATUS_06"),
    WH_STATUS_07("WH_STATUS_07"),
    WH_STATUS_08("WH_STATUS_08"),
    WH_STATUS_09("WH_STATUS_09"),
    WH_STATUS_10("WH_STATUS_10"),
    WH_STATUS_11("WH_STATUS_11"),
    WH_STATUS_12("WH_STATUS_12"),
    WH_STATUS_13("WH_STATUS_13"),
    WH_STATUS_14("WH_STATUS_14"),
    WH_STATUS_15("WH_STATUS_15"),
    WH_STATUS_16("WH_STATUS_16"),
    WH_STATUS_17("WH_STATUS_17"),
    WH_STATUS_18("WH_STATUS_18"),
    WH_STATUS_19("WH_STATUS_19"),
    WH_STATUS_20("WH_STATUS_20"),
    WH_STATUS_21("WH_STATUS_21"),
    WH_STATUS_22("WH_STATUS_22"),
    WH_STATUS_23("WH_STATUS_23"),
    WH_STATUS_24("WH_STATUS_24"),	
	
	WH_CHAN_TYPE("WH_CHAN_TYPE"),
	WH_VALUE_OK("WH_OK"),
	WH_HSKV("WH_HSKV"),	
	WH_APP_BORROW("WH_APP_BORROW"),
	WH_APP_BORROW_CV("WH_APP_BORROW_CV"), 
	WH_APP_BORROW_HD("WH_APP_BORROW_HD"),
	WH_APP_RE_BORROW_HD("WH_APP_RE_BORROW_HD"), 
	WH_APP_RE_BORROW_CV("WH_APP_RE_BORROW_CV"), 
	WH_APP_CAVET_BR("WH_APP_CAVET_BR"),
	
		//Other module
	LEAD_GEN("LEAD_GEN"),
	AMO("AMO"),
	TC("TC"), // TRUST_CONNECT
	GC("GC"),
    MIS("MIS"),
    XSELL_APP_ACTIVE("XSELL_APP_ACTIVE"),
    XSELL_APP_IN_ACTIVE("XSELL_APP_IN_ACTIVE"),
    XSELL_APP_OK("XSELL_APP_OK"),
    XSELL_APP_REJECT("XSELL_APP_REJECT"),
    XSELL_APP_WAIT("XSELL_APP_WAIT"),
    
    MOTORBIKE("MOTORBIKE"),
    EMOTORBIKE("EMOTORBIKE"),
    CX("CX"),

    UPL_SRC_MB_HN("HN"),
    UPL_SRC_MB_HCM("HCM"),
    UPL_CODE_MB_HN("MB-HN"),
    UPL_CODE_MB_HCM("MB-HCM"),
    
    //Mobile4Sale
    ABORT_CASE("ABORT_CASE"),
    BPM_REUPLOAD("BPM_REUPLOAD"),
    BPM_RETURN_EDIT_CASE("BPM_RETURN_EDIT_CASE"),
    UPLOAD_BPM_FAILD("UPLOAD_BPM_FAILD"),
    UPLOAD_BPM_SUCCESS("UPLOAD_BPM_SUCCESS"),
    NEW("NEW"),
    ROUTE_CASE_SUCCESS("ROUTE_CASE_SUCCESS"),
    ROUTE_CASE_FAIL("ROUTE_CASE_FAIL"),
    RECEIVE_IMAGE_SUCCESS("RECEIVE_IMAGE_SUCCESS"),
    MFS_OTHER_REASON("MFS_OTHER_REASON"),
    MFS_CUST_NOT_NEED_BORROW("MFS_CUST_NOT_NEED_BORROW"),

    WH_NOT("WH_NOT"),
    //warehouse f2
    WH_EXPORT_PAPER_RECEIPT("WH_EXPORT_PAPER_RECEIPT"),    
    WH_EXPECTED_LOAN_DOC("WH_EXPECTED_LOAN_DOC"),
    WH_EXPECTED_CAVET("WH_EXPECTED_CAVET"),
    TSA("TSA"),
    DSA("DSA"),
    
    WH_ONE("WH_ONE"),
    POS_ABORT("POS_ABORT"),
    POS_OPEN("POS_OPEN"),
    WH_MANY("WH_MANY"),
    
    MOBILE("MOBILE"),
    CUSTOMER("CUSTOMER"),
    PERMANENT("PERMANENT"),
    WH_APP_RETURN("WH_APP_RETURN"),  
    
    TRANS_APP_REJECT("TRANS_APP_REJECT"),
    TRANS_APP_OK("TRANS_APP_OK"),
    TRANS_APP_WAIT("TRANS_APP_WAIT"),
    TRANS_C("TRANS_C"),
    TRANS_P("TRANS_P"),
    TRANS_I("TRANS_I"),
    TRANS_OP_I("TRANS_OP_I"),
    TRANS_OP_A("TRANS_OP_A"),
    TRANS_OP_D("TRANS_OP_D"),
    TRANS_OP_U("TRANS_OP_U"),
    TRANS_OP_N("TRANS_OP_N"),
    PROD_SCHEDULE("PROD_SCHEDULE"),


    OTHERS("OTHERS"),
    CAT_A("CAT_A"),
    CAT_B("CAT_B"),
    CAT_C("CAT_C"),

    CUST_IDTYP_1("1"),
    PAY_FRN_CONTRACTOR("PAY_FRN_CONTRACTOR"),
    ECO_ORG("ECO_ORG"),
    SUB_UNIT("SUB_UNIT"),
    DIP_INT_ORG("DIP_INT_ORG"),

	
	// Product Manager 
    PRD_SC_GROUP_OTHER("OTHER"),
    PRD_SC_GROUP_ALL("ALL"),
    PRD_SC_GROUP_HT("HT"),
    PRD_SC_GROUP_NHT("NHT"),
    PRD_AUDIT_CREATE("N"),
    PRD_AUDIT_UPDATE("U"),
    PRD_AUDIT_ACTIVE("A"),
    PRD_AUDIT_INACTIVE("I"),
    PRD_AUDIT_DELETE("D"),
	
	PRD_CHANNEL_CD("CD"),
	PRD_CHANNEL_TW("TW"),
	
	PRD_UPL_TYPE_GOODS("GOODS");


    private final String value;

    CTCodeValue1(String value) {
        this.value = value;
    }

    public static CTCodeValue1 from(String text) {
        for (CTCodeValue1 b : CTCodeValue1.values()) {
            if (b.value.equalsIgnoreCase(text)) {
                return b;
            }
        }
        return null;
    }

    public String value() {
        return this.value;
    }
}
