package com.mcredit.model.enums;

public enum ParametersName {
	
	STRING("S"),
	INTERGER("I"),
	LONG("L"),
	BIGDECIMAL("N"),
	DATE("D"),	
	ESB_HOST("ESB_HOST"),
	ESB_HOST_MOCK("ESB_HOST_MOCK"),
	PORTAL_HOST("PORTAL_HOST"),
	ECM_HOST("ECM_HOST"),
	AD_HOST("AD_HOST"),
	AD_PORT("AD_PORT"),
	AD_ROOTDN("AD_ROOTDN"),
	REDIS_HOST("REDIS_HOST"),
	FEE_COLLECT_AMT("FEE_COLLECT_AMT"),
	CARD_NOTIFY_DATE("CARD_NOTIFY_DATE"),
	FILE_DIRECTORY("FILE_DIRECTORY"),
	TMP_FOLDER_UPLOAD_DEBT_HOME("TMP_FOLDER_UPLOAD_DEBT_HOME"),
	TMP_FOLDER_CAPTURE_DEBT_HOME("TMP_FOLDER_CAPTURE_DEBT_HOME"),
	TMP_FOLDER_BPM_DATA_FILE_FAS("TMP_FOLDER_BPM_DATA_FILE_FAS"),
	FOLDER_BPM_DATA_FILE("FOLDER_BPM_DATA_FILE"),
	AD_ADMIN_USERNAME("AD_ADMIN_USERNAME"),
	AD_ADMIN_PASSWORD("AD_ADMIN_PASSWORD"),
	SCORE_CARD_DIRECTORY("SCORE_CARD_DIRECTORY"),
	/* begin config ECM */
	ECM_TOKENT("ECM_TOKENT"),
	ECM_USERNAME("ECM_USERNAME"),
	ECM_PASSWORD("ECM_PASSWORD"),	
	ECM_BUILDVERSION("ECM_BUILDVERSION"),
	ECM_TOKENT_TYPE("ECM_TOKENT_TYPE"),
	ECM_PROCESSID_DE("ECM_PROCESSID_DE"),
	ECM_PROCESSID_CL("ECM_PROCESSID_CL"),
	ECM_PROCESSID_IL("ECM_PROCESSID_IL"),
	WH_ECM_SHARE_LINK("WH_ECM_SHARE_LINK"),
	ECM_PARTITIONSIZE("ECM_PARTITIONSIZE"),
	ECM_THREADPOOLSIZE("ECM_THREADPOOLSIZE"),	
	ECM_LOCALROOTFOLDER("ECM_LOCALROOTFOLDER"),	
	ECM_LOADDOCUMENTPATH("ECM_LOADDOCUMENTPATH"),	
	ECM_THREAD_POOL_MAXIDLE("ECM_THREAD_POOL_MAXIDLE"),
	ECM_THREAD_POOL_MAXTOTAL("ECM_THREAD_POOL_MAXTOTAL"),
	ECM_SESSION_POOL_MAXIDLE("ECM_SESSION_POOL_MAXIDLE"),
	ECM_SESSION_POOL_MAXTOTAL("ECM_SESSION_POOL_MAXTOTAL"),	
	/* Prefix path on remote server */
	ECM_PREFIX_SERVER_BPM_FILE("ECM_PREFIX_SERVER_BPM_FILE"),	
	ECM_PREFIX_SERVER_DE_FILE("ECM_PREFIX_SERVER_DE_FILE"),	
	ECM_PREFIX_SERVER_DEBT_COL("ECM_PREFIX_SERVER_DEBT_COL"),	
	ECM_PREFIX_SERVER_FAS("ECM_PREFIX_SERVER_FAS"),	
	/* DE configuration for FTP server */
	ECM_LOCAL_DE_BASE_PATH("ECM_LOCAL_DE_BASE_PATH"),
	ECM_DE_FTP_REMOTE_SERVER("ECM_DE_FTP_REMOTE_SERVER"),
	ECM_DE_FTP_REMOTE_PORT("ECM_DE_FTP_REMOTE_PORT"),
	ECM_DE_FTP_REMOTE_USER("ECM_DE_FTP_REMOTE_USER"),
	ECM_DE_FTP_REMOTE_PASSWORD("ECM_DE_FTP_REMOTE_PASSWORD"),
	/* IL configuration for BPM server */
	ECM_REMOTE_IL_BASE_PATH("ECM_REMOTE_IL_BASE_PATH"),
	ECM_IL_FTP_REMOTE_SERVER("ECM_IL_FTP_REMOTE_SERVER"),
	ECM_IL_FTP_REMOTE_PORT("ECM_IL_FTP_REMOTE_PORT"),
	ECM_IL_FTP_REMOTE_USER("ECM_IL_FTP_REMOTE_USER"),
	ECM_IL_FTP_REMOTE_PASSWORD("ECM_IL_FTP_REMOTE_PASSWORD"),
	ECM_LOCAL_IL_BASE_PATH("ECM_LOCAL_IL_BASE_PATH"),
	/* DE configuration for BPM server */
	ECM_DE_BPM_FTP_REMOTE_SERVER("ECM_DE_BPM_FTP_REMOTE_SERVER"),
	ECM_DE_BPM_FTP_REMOTE_PORT("ECM_DE_BPM_FTP_REMOTE_PORT"),
	ECM_DE_BPM_FTP_REMOTE_USER("ECM_DE_BPM_FTP_REMOTE_USER"),
	ECM_DE_BPM_REMOTE_PASSWORD("ECM_DE_BPM_REMOTE_PASSWORD"),
	ECM_REMOTE_DE_BASE_PATH("ECM_REMOTE_DE_BASE_PATH"),
	/* FAS configuration for file server */
	ECM_REMOTE_FAS_BASE_PATH("ECM_REMOTE_FAS_BASE_PATH"),
	ECM_FAS_FTP_REMOTE_SERVER("ECM_FAS_FTP_REMOTE_SERVER"),
	ECM_FAS_FTP_REMOTE_PORT("ECM_FAS_FTP_REMOTE_PORT"),
	ECM_FAS_FTP_REMOTE_USER("ECM_FAS_FTP_REMOTE_USER"),
	ECM_FAS_FTP_REMOTE_PASSWORD("ECM_FAS_FTP_REMOTE_PASSWORD"),
	ECM_LOCAL_FAS_BASE_PATH("ECM_LOCAL_FAS_BASE_PATH"),
	ECM_FAS_FILE_TEST_CONNECTION("ECM_FAS_FILE_TEST_CONNECTION"),
	ECM_FAS_DOCUMENT_TYPE("ECM_FAS_DOCUMENT_TYPE"),
	ECM_FAS_CONTENT_FOLDER("ECM_FAS_CONTENT_FOLDER"),
	/* Debt Collection configuration for BPM server */
	ECM_REMOTE_DC_BASE_PATH("ECM_REMOTE_DC_BASE_PATH"),
	ECM_DC_FTP_REMOTE_SERVER("ECM_DC_FTP_REMOTE_SERVER"),
	ECM_DC_FTP_REMOTE_PORT("ECM_DC_FTP_REMOTE_PORT"),
	ECM_DC_FTP_REMOTE_USER("ECM_DC_FTP_REMOTE_USER"),
	ECM_DC_FTP_REMOTE_PASSWORD("ECM_DC_FTP_REMOTE_PASSWORD"),
	ECM_LOCAL_DC_BASE_PATH("ECM_LOCAL_DC_BASE_PATH"),
	/* End config ECM */
	TOKEN_EXPIRED_TIME("TOKEN_EXPIRED_TIME"),
	WH_THANKS_LETTER_TEMPLATE("WH_THANKS_LETTER_TEMPLATE"),
	WH_PATH_THANKS_LETTER("WH_PATH_THANKS_LETTER"),
	WH_THANKS_LETTER_ZIP_FILE("WH_THANKS_LETTER_ZIP_FILE"),
	WH_THANKS_LETTER_FILE_NAME("WH_THANKS_LETTER_FILE_NAME"),
	WH_PATH_HANDOVER_EXPORT("WH_PATH_HANDOVER_EXPORT"),
	WH_HANDOVER_EXPORT_FILE_NAME("WH_HANDOVER_EXPORT_FILE_NAME"),
	WH_HANDOVER_EXPORT_ZIP_FILE("WH_HANDOVER_EXPORT_ZIP_FILE"),
	WH_PAPER_RECEIPT_TEMPLATE("WH_PAPER_RECEIPT_TEMPLATE"),
	WH_PATH_PAPER_RECEIPT("WH_PATH_PAPER_RECEIPT"),
	WH_PAPER_RECEIPT_ZIP_FILE("WH_PAPER_RECEIPT_ZIP_FILE"),
	WH_PAPER_RECEIPT_FILE_NAME("WH_PAPER_RECEIPT_FILE_NAME"),
	WH_BODY_ERR_MAIL("WH_BODY_ERR_MAIL"),
	DB_CHANGES_CONNECTION_URL("DB_CHANGES_CONNECTION_URL"),
	DB_CHANGES_CONNECTION_USER("DB_CHANGES_CONNECTION_USER"),
	DB_CHANGES_CONNECTION_PASSWORD("DB_CHANGES_CONNECTION_PASSWORD"),
	
	NUMBER_PARALLEL_CAPTURE_ECM("NUMBER_PARALLEL_CAPTURE_ECM"),
	TMP_FOLDER_CAPTURE_DOCUMENT_ECM("TMP_FOLDER_CAPTURE_DOCUMENT_ECM"),
	
	//dongtd.ho: add kafka config
	KAFKA_BOOTSTRAP_SERVER("KAFKA_BOOTSTRAP_SERVER"),
	KAFKA_QRCODE_TOPIC("KAFKA_QRCODE_TOPIC"),
	KAFKA_QRCODE_GROUP("KAFKA_QRCODE_GROUP"),
	KAFKA_CACHE_GROUP("KAFKA_CACHE_GROUP"),
	KAFKA_CACHE_TOPIC("KAFKA_CACHE_TOPIC"),
	
	MANAGE_PROFILE_OP_CENTRAL_EMAIL("MANAGE_PROFILE_OP_CENTRAL_EMAIL"),
	MANAGE_PROFILE_OP_CENTRAL_USER("MANAGE_PROFILE_OP_CENTRAL_USER"),
	MANAGE_PROFILE_OP_CENTRAL_PASSWORD_EMAIL("MANAGE_PROFILE_OP_CENTRAL_PASSWORD_EMAIL"),


	// Mobile for sales
	MFS_CLIENT_ID("MFS_CLIENT_ID"),
	MFS_CLIENT_SECRET("MFS_CLIENT_SECRET"),
	MFS_FTP_HOST("MFS_FTP_HOST"),
	MFS_FTP_USER("MFS_FTP_USER"),
	MFS_FTP_PASSWORD("MFS_FTP_PASSWORD"),
	MFS_FTP_PORT("MFS_FTP_PORT"),
	MFS_TEMP_DIR("MFS_TEMP_DIR"),
	MFS_CREATE_CASE_TAS_UID("MFS_CREATE_CASE_TAS_UID"),
	MFS_CREATE_CASE_PRO_UID("MFS_CREATE_CASE_PRO_UID"),
	MFS_PROCESS_ID("MFS_PROCESS_ID"),
	MFS_TASK_ID("MFS_TASK_ID"),
	MFS_WHITE_LIST("MFS_WHITE_LIST"),
	MFS_FTP_ROOT_FOLDER("MFS_FTP_ROOT_FOLDER"),
	MFS_AUTH_KEY_FCM("MFS_AUTH_KEY_FCM"),
	MFS_API_URL_FCM("MFS_API_URL_FCM"),
	MFS_MESSAGE_REPORT("MFS_MESSAGE_REPORT"),
	
	MFS_PATH_MIGRATED_DATA("MFS_PATH_MIGRATED_DATA"),
	MFS_DATE_MIGRATED_DATA("MFS_DATE_MIGRATED_DATA"), 
	MFS_CALLOUT_TEST("MFS_CALLOUT_TEST"), 
	MFS_DEFAULT_MIN_LOAN_AMOUNT("MFS_DEFAULT_MIN_LOAN_AMOUNT"), 
	MFS_DEFAULT_MAX_LOAN_AMOUNT("MFS_DEFAULT_MAX_LOAN_AMOUNT"), 
	MFS_DEFAULT_MIN_LOAN_TENOR("MFS_DEFAULT_MIN_LOAN_TENOR"), 
	MFS_DEFAULT_MAX_LOAN_TENOR("MFS_DEFAULT_MAX_LOAN_TENOR"), 
	MFS_PROCESS_ID_INSTALLMENT("MFS_PROCESS_ID_INSTALLMENT"), 
	MFS_TASK_ID_INSTALLMENT("MFS_TASK_ID_INSTALLMENT"),
	MFS_TOKEN_EXPIRED_TIME("MFS_TOKEN_EXPIRED_TIME"),
	MFS_XSECURITY_LIST("MFS_XSECURITY_LIST"),
	MFS_ENABLE_XSECURITY("MFS_ENABLE_XSECURITY"), 
	MFS_ENABLE_NOTIFICATION_THIRD_PARTY("MFS_ENABLE_NOTIFICATION_THIRD_PARTY"),
        //warehouse f2
	WH_EXPORT_PAPER_RECEIPT("WH_EXPORT_PAPER_RECEIPT"),
    WH_PATH_HANDOVER_BORR_EXPORT("WH_PATH_HANDOVER_BORR_EXPORT"),
    WH_HANDOVER_BORR_EXPORT_FILE_NAME("WH_HANDOVER_BORR_EXPORT_FILE_NAME"),
    WH_HANDOVER_BORR_EXPORT_ZIP_FILE("WH_HANDOVER_BORR_EXPORT_ZIP_FILE"),   
    WH_THANKS_LETTER_TEMPLATE_F1("WH_THANKS_LETTER_TEMPLATE_F1"),   
    WH_THANKS_LETTER_TEMPLATE_F2("WH_THANKS_LETTER_TEMPLATE_F2"),   
    WH_EXPORT_THANK_LETTER("WH_EXPORT_THANK_LETTER"),
    WH_PATH_HISTORY_EXPORT("WH_PATH_HISTORY_EXPORT"),
    WH_EXPORT_HISTORY("WH_EXPORT_HISTORY"), 
	
	// Assign Permissions
	KAFKA_TOPIC_REFRESH_CACHE("KAFKA_TOPIC_REFRESH_CACHE"),
	KAFKA_GROUP_REFRESH_CACHE("KAFKA_GROUP_REFRESH_CACHE"), 
	
	// Audit
	LOCAL_AUDIT_FILE_ADDRESS("LOCAL_AUDIT_FILE_ADDRESS"), 
	AUDIT_MB_CONFIG("AUDIT_MB_CONFIG"), 
	AUDIT_MOMO_CONFIG("AUDIT_MOMO_CONFIG"), 
	AUDIT_PAYOO_CONFIG("AUDIT_PAYOO_CONFIG"), 
	AUDIT_VNPTEPAY_CONFIG("AUDIT_VNPTEPAY_CONFIG"), 
	AUDIT_VNPOST_CONFIG("AUDIT_VNPOST_CONFIG"),
	GET_QRCODE_URL("GET_QRCODE_URL"),
	FILE_EXPORT_GENDOC("FILE_EXPORT_GENDOC"),
	AUDIT_VIETTEL_CONFIG("AUDIT_VIETTEL_CONFIG"),
	
	//for one time password (token)

	OTP_TOKEN_EXPIRED_TIME("OTP_TOKEN_EXPIRED_TIME"),
	VNPOST_17H_CONFIG("VNPOST_17H_CONFIG"),
	
	/*CancelCaseBPM*/
	NUMBER_PARALLEL_CANCEL_CASE_BPM("NUMBER_PARALLEL_CANCEL_CASE_BPM"),
	TOKEN_CANCEL_CASE_BPM("TOKEN_CANCEL_CASE_BPM"),
	REFESH_TOKEN_CANCEL_CASE_BPM("REFESH_TOKEN_CANCEL_CASE_BPM"),
	USR_UID_TARGET("USR_UID_TARGET"),
	AUTO_ABORT_CLIENT_ID("AUTO_ABORT_CLIENT_ID"),
	AUTO_ABORT_CLIENT_SECRET("AUTO_ABORT_CLIENT_SECRET"),
	AUTO_ABORT_USER("AUTO_ABORT_USER"),
	AUTO_ABORT_PASS("AUTO_ABORT_PASS"),
	NUMBER_DSS_PAGESIZE("NUMBER_DSS_PAGESIZE"),
	AUTO_ABORT_EMAIL("AUTO_ABORT_EMAIL"),
	AUTO_ABORT_EMAIL_SMTP_USER("AUTO_ABORT_EMAIL_SMTP_USER"),
	AUTO_ABORT_EMAIL_SMP_PASS("AUTO_ABORT_EMAIL_SMP_PASS"),
	// Rule
	RULE_CACHE_DATE_PARAM_EFFECTIVE("RULE_CACHE_DATE_PARAM_EFFECTIVE"),        
	ACTIVE_INACTIVE_PRODUCT_EMAIL("ACTIVE_INACTIVE_PRODUCT_EMAIL"),
	ACTIVE_INACTIVE_PRODUCT_PASSWORD_EMAIL("ACTIVE_INACTIVE_PRODUCT_PASSWORD_EMAIL"),
	ACTIVE_INACTIVE_PRODUCT_USER("ACTIVE_INACTIVE_PRODUCT_USER"),

	// appraisal product group by product_name
	PRD_GRP_MILITARY("PRD_GRP_MILITARY"),
	PRD_GRP_CS_SY("PRD_GRP_CS_SY"),
	PRD_GRP_CS_EVN("PRD_GRP_CS_EVN"),
	PRD_GRP_CS_INSURANCE("PRD_GRP_CS_INSURANCE"),
	PRD_GRP_CS_BANK_ACCT("PRD_GRP_CS_BANK_ACCT"),

	OCR_BASH_FILE_ADDR("OCR_BASH_FILE_ADDR"), 
	QR_CODE_CLIENT_ID("QR_CODE_CLIENT_ID"), 
	QR_CODE_CLIENT_SECRET("QR_CODE_CLIENT_SECRET"), 
	QR_CODE_USER_NAME("QR_CODE_USER_NAME"), 
	QR_CODE_PASS_WORD("QR_CODE_PASS_WORD"), 
	FILE_QR_CODE("FILE_QR_CODE"),

	// appraisal product group for income interpolate
	PRD_GRP_INCOME_INTERPOLATE("PRD_GRP_INCOME_INTERPOLATE"),
	AUDIT_VNPOST_17H_CONFIG("AUDIT_VNPOST_17H_CONFIG"),
	
	// common user
	COMMON_USERNAME("COMMON_USERNAME"),
	COMMON_PASSWORD("COMMON_PASSWORD"),

	// Product 
	FILE_DIRECTORY_PROD("FILE_DIRECTORY_PROD"),
	
	// Check CIC
	CIC_RESULT_EXPIRE_DAYS("CIC_RESULT_EXPIRE_DAYS"),
	CIC_RESULT_DIR("CIC_RESULT_DIR"),
	CIC_AUTO_CREATE_REQ_TIME("CIC_AUTO_CREATE_REQ_TIME"),
	BPM_PROCESS_ID_CONCENTRATING("BPM_PROCESS_ID_CONCENTRATING"),
	CIC_NOTIFICATIONS_EMAIL("CIC_NOTIFICATIONS_EMAIL"),
	CIC_NOTIFICATIONS_EMAIL_SMTP_PASS("CIC_NOTIFICATIONS_EMAIL_SMTP_PASS"),
	CIC_NOTIFICATIONS_EMAIL_SMTP_USER("CIC_NOTIFICATIONS_EMAIL_SMTP_USER"),
	
	// Send sms job
	SMS_RECORDS_LIMIT("SMS_RECORDS_LIMIT"),
	SMS_QUEUE_PATH("SMS_QUEUE_PATH"),
	
	// TS report lead key
	TS_LEAD_REPORT_BANK_CODE("TS_LEAD_REPORT_BANK_CODE"),
	TS_LEAD_REPORT_BANK_API_KEY("TS_LEAD_REPORT_BANK_API_KEY"),
	
	// Gendoc: products, period repayment date
	GENDOC_ENDOW_PRODUCT_LIST("GENDOC_ENDOW_PRODUCT_LIST"),
	GENDOC_LIMIT_PRODUCT_LIST("GENDOC_LIMIT_PRODUCT_LIST"),
	GENDOC_CONTRACT_DATE("GENDOC_CONTRACT_DATE"),
	GENDOC_PERIOD_REPAYMENT_DATE("GENDOC_PERIOD_REPAYMENT_DATE"),

	//send mail return VH
	NOTIFICATION_VHGN_EMAIL("NOTIFICATION_VHGN_EMAIL"),
	NOTIFICATION_VHGN_SMTP_USER("NOTIFICATION_VHGN_SMTP_USER"),
	NOTIFICATION_VHGN_EMAIL_SMTP_PASS("NOTIFICATION_VHGN_EMAIL_SMTP_PASS")
	;
	
	private final String value;

	ParametersName(String value) {
		this.value = value;
	}

	public String value() {
		return this.value;
	}
}
