package com.mcredit.model.enums;

public enum RuleCode {

	WH_DOCUMENT("WH_DOCUMENT"),
	CORP_TYPE("CORP_TYPE"),
	PREPAY_RATE("PREPAY_RATE"),
	CAT_TYPE("CAT_TYPE"),
	CHECKLIST_ENTRY("CHECKLIST_ENTRY"),
	CHECKLIST_EXPT("CHECKLIST_EXPT"),
	OPERATION_REGIONS("OPERATION_REGIONS"),
	AGE_VALIDATION("AGE_VALIDATION"),
	COURIER_VALIDATION("COURIER_VALIDATION"),
	RM_CODEFIELD("RM_CODEFIELD"),
	APPRAISAL_VALIDATION("APPRAISAL_VALIDATION"),
	GOODS_VALIDATION("GOODS_VALIDATION"),
	IDENTITY_EXPIRATION("IDENTITY_EXPIRATION"),
	RM_PILOT("RM_PILOT"),
	CHECKLIST_PILOT("CHECKLIST_PILOT"),
	INCOME_VALIDATION("INCOME_VALIDATION"),
	PROVINCE_BLOCK("PROVINCE_BLOCK"),
	RM_SIP_0PERCENT("RM_SIP_0PERCENT"),
	SR_MASTER_PROGRAM("SR_MASTER_PROGRAM"),
	SR_CHILD_PROGRAM001("SR_CHILD_PROGRAM001"),
	SR_CHILD_PROGRAM002("SR_CHILD_PROGRAM002"),
	SR_CHILD_PROGRAM003("SR_CHILD_PROGRAM003"),
	SR_CHILD_PROGRAM004("SR_CHILD_PROGRAM004"),
	SR_PROGRAM("SR_PROGRAM"),
	CHECK_DTI_PTI("CHECK_DTI_PTI");

	private final String value;

	RuleCode(String value) {
		this.value = value;
	}

	public String value() {
		return this.value;
	}

}
