package com.mcredit.rule.engine.generalScoreDate

import java.util.Date;
import java.text.SimpleDateFormat;
import com.mcredit.model.object.RuleObject;
import java.util.Calendar;
import java.text.DateFormat;

global com.mcredit.rule.FormulaResult formulaResult;

function String getVal(String val, int len, int max) {
	String ret = val;
	int start = 0;
	if(val == null) {
		ret = "";
	} else {
		start = val.length();
	}
	for(int i=start;i<len-1;i++) {
		ret = ret + "N";
	}
	if(len < max) {
		ret = ret + "Y";
	} else if(ret.length() < max - 1) {
		ret = ret + "N";
	}

	return ret;
}


function Date plusMonths(Date input , int month){
	Calendar c = Calendar.getInstance();
		c.setTime(input);
		c.add(Calendar.MONTH, month);
		return c.getTime();
}

function Date plusDate(Date input , int days){
	Calendar c = Calendar.getInstance();
		c.setTime(input);
		c.add(Calendar.DATE, days);
		return c.getTime();
}
function Date plusYear(Date input , int years){
		Calendar c = Calendar.getInstance();
		c.setTime(input);
		c.add(Calendar.YEAR, years);
		return c.getTime();
}

function Date toDate(String input){
	Date date = null ;
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	
	try {
		date = sdf.parse(input.substring(0, 10));
	} catch (Exception e) {
		e.printStackTrace();
	}
	
	return date;
}

rule "Check LG TS Date <= 09/01/2020"
	when
		RuleObject(lgTsScoreDate != null && lgTsScoreDate != "" && !toDate(lgTsScoreDate).after(toDate("2020-01-09")))
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 1, 1000));
end

rule "Check LG TS Date >= 10/01/2020"
	when
		RuleObject(lgTsScoreDate != null && lgTsScoreDate != ""  && !toDate(lgTsScoreDate).before(toDate("2020-01-10")))
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 2, 1000));
end

rule "Check TS Date <= 28/04/2020"
	when
		RuleObject(tsScoreDate != null && tsScoreDate != ""  && !toDate(tsScoreDate).after(toDate("2020-04-28")))
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 3, 1000));
end

rule "Check TS Date >= 29/04/2020"
	when
		RuleObject(tsScoreDate != null && tsScoreDate != "" && !toDate(tsScoreDate).before(toDate("2020-04-29")))
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 4, 5));
end

