package com.mcredit.rule.engine.numberBills;

import com.mcredit.model.object.RuleObject;

global com.mcredit.rule.FormulaResult formulaResult;

function String getVal(String val, int len, int max) {
	String ret = val;
	int start = 0;
	if(val == null) {
		ret = "";
	} else {
		start = val.length();
	}
	for(int i=start;i<len-1;i++) {
		ret = ret + "N";
	}
	if(len < max) {
		ret = ret + "Y";
	} else if(ret.length() < max - 1) {
		ret = ret + "N";
	}

	return ret;
}

rule "Check number of bills == 1"
	when
		RuleObject(numberBills != null && numberBills == 1)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 1, 3));
end

rule "Check number of bills >= 2"
	when
		RuleObject(numberBills != null && numberBills >= 2)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 2, 3));
end
