package com.mcredit.rule.engine.amtAfterInsurance

import com.mcredit.model.object.RuleObject;

global com.mcredit.rule.FormulaResult formulaResult;

function String getVal(String val, int len, int max) {
	String ret = val;
	int start = 0;
	if(val == null) {
		ret = "";
	} else {
		start = val.length();
	}
	for(int i=start;i<len-1;i++) {
		ret = ret + "N";
	}
	if(len < max) {
		ret = ret + "Y";
	} else if(ret.length() < max - 1) {
		ret = ret + "N";
	}

	return ret;
}

rule "Check range [0M - 10M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 0 && loanAmountAfterInsurrance < 10000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 1, 1000));

end

rule "Check range [10M - 15M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 10000000 && loanAmountAfterInsurrance < 15000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 2, 1000));

end

rule "Check range [0M - 50M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 0 && loanAmountAfterInsurrance < 50000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 3, 1000));

end

rule "Check range [45M - 50M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 45000000 && loanAmountAfterInsurrance < 50000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 4, 1000));

end

rule "Check range [35M - 50M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 35000000 && loanAmountAfterInsurrance < 50000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 5, 1000));

end

rule "Check range [40M - 50M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 40000000 && loanAmountAfterInsurrance < 50000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 6, 1000));

end

rule "Check range [50M - 100M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 50000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 7, 1000));

end

rule "Check range [0M - 45M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 0 && loanAmountAfterInsurrance < 45000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 8, 1000));

end

rule "Check range [45M - 100M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 45000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 9, 1000));

end

rule "Check range [0M - 35M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 0 && loanAmountAfterInsurrance < 35000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 10, 1000));

end

rule "Check range [35M - 100M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 35000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 11, 1000));

end

rule "Check range [0M - 40M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 0 && loanAmountAfterInsurrance < 40000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 12, 1000));

end

rule "Check range [40M - 100M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 40000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 13, 1000));

end

rule "Check range [10M - 35M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 10000000 && loanAmountAfterInsurrance < 35000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 14, 1000));

end

rule "Check range [10M - 20M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 10000000 && loanAmountAfterInsurrance < 20000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 15, 1000));

end

rule "Check range [20M - 35M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 20000000 && loanAmountAfterInsurrance < 35000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 16, 1000));

end

rule "Check range [10M - 100M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 10000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 17, 1000));

end

rule "Check range [0M - 15M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 0 && loanAmountAfterInsurrance < 15000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 18, 1000));

end

rule "Check range [15M - 20M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 15000000 && loanAmountAfterInsurrance < 20000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 19, 1000));

end

rule "Check range [15M - 35M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 15000000 && loanAmountAfterInsurrance < 35000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 20, 1000));

end

rule "Check range [0 - 10]"
	when
		RuleObject(loanAmountAfterInsurrance >= 0 && loanAmountAfterInsurrance <= 10000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 21, 1000));

end

rule "Check range (10M - 35M)"
	when
		RuleObject(loanAmountAfterInsurrance > 10000000 && loanAmountAfterInsurrance < 35000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 22, 1000));

end

rule "Check range [45M - 50M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 45000000 && loanAmountAfterInsurrance <= 50000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 23, 1000));

end

rule "Check range [50M]"
	when
		RuleObject(loanAmountAfterInsurrance == 50000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 24, 1000));

end

rule "Check range [20M - 100M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 20000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 25, 1000));

end

rule "Check range [5M - max)"
	when
		RuleObject(loanAmountAfterInsurrance >= 5000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 26, 1000));

end

rule "Check range [15M - max)"
	when
		RuleObject(loanAmountAfterInsurrance >= 15000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 27, 1000));

end

rule "Check range [20M]"
	when
		RuleObject(loanAmountAfterInsurrance == 20000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 28, 1000));

end

rule "Check range (20M - 30M]"
	when
		RuleObject(loanAmountAfterInsurrance > 20000000 && loanAmountAfterInsurrance <= 30000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 29, 1000));

end

rule "Check range (30M - 35M)"
	when
		RuleObject(loanAmountAfterInsurrance > 30000000 && loanAmountAfterInsurrance < 35000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 30, 1000));

end

rule "Check range [15M - 20M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 15000000 && loanAmountAfterInsurrance <= 20000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 31, 1000));

end

rule "Check range (20M - 35M)"
	when
		RuleObject(loanAmountAfterInsurrance > 20000000 && loanAmountAfterInsurrance < 35000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 32, 1000));

end

rule "Check range [0M - 70M)"
	when
		RuleObject(loanAmountAfterInsurrance >= 0 && loanAmountAfterInsurrance < 70000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 33, 1000));

end

rule "Check range [70M - max)"
	when
		RuleObject(loanAmountAfterInsurrance >= 70000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 34, 1000));

end

rule "Check range (10M - 20M)"
	when
		RuleObject(loanAmountAfterInsurrance > 10000000 && loanAmountAfterInsurrance < 20000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 35, 1000));

end

rule "Check range [50M - 70M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 50000000 && loanAmountAfterInsurrance <= 70000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 36, 1000));

end

rule "Check range (70M - max)"
	when
		RuleObject(loanAmountAfterInsurrance > 70000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 37, 1000));
end

rule "Check range [0 - 20M)"
	when
		RuleObject(loanAmountAfterInsurrance < 20000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 38, 1000));
end

rule "Check range [20M - 30M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 20000000 && loanAmountAfterInsurrance <= 30000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 39, 1000));
end

rule "Check range [30M - max)"
	when
		RuleObject(loanAmountAfterInsurrance >= 30000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 40, 1000));
end

rule "Check range [0 - 30M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 0 && loanAmountAfterInsurrance <= 30000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 41, 1000));
end

rule "Check range [15M - 30M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 15000000 && loanAmountAfterInsurrance <= 30000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 42, 1000));
end

rule "Check range [10M - 30M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 10000000 && loanAmountAfterInsurrance <= 30000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 43, 1000));
end

rule "Check range [0 - 70M)"
	when
		RuleObject(loanAmountAfterInsurrance <= 70000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 44, 1000));
end

rule "Check range [35M - 70M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 35000000 && loanAmountAfterInsurrance <= 70000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 45, 1000));
end

rule "Check range [45M - 70M]"
	when
		RuleObject(loanAmountAfterInsurrance >= 45000000 && loanAmountAfterInsurrance <= 70000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 46, 1000));
end

rule "Check range [0 - 15M]"
	when
		RuleObject(loanAmountAfterInsurrance <= 15000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 47, 1000));
end

rule "Check range [15.01M - 20M]"
	when
		RuleObject(loanAmountAfterInsurrance > 15000000 && loanAmountAfterInsurrance <= 20000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 48, 1000));
end

rule "Check range [30.01M - max)"
	when
		RuleObject(loanAmountAfterInsurrance > 30000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 49, 1000));
end

rule "Check range [0 - 20M]"
	when
		RuleObject(loanAmountAfterInsurrance <= 20000000)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 50, 1000));
end

rule "Check range 0 - 100M"
	when
		RuleObject(loanAmountAfterInsurrance >= 0)
	then
		formulaResult.setStringValue(getVal(formulaResult.getStringValue(), 51, 51));

end
